### ISSUE TITLE
Allow attic cache

### ISSUE THREAD

**Issue by drestrepom** [fluidattacks/makes#1007]
Allow the use of [attic](https://github.com/zhaofengli/attic) cache 
- push to the server
- configure substitutes to pull the cache

**Comment by dsalaza4** [comment]
Closing this as:

- Installation was too difficult
- Configurations differed from Cachix ones
- Performance gain was minimum
- Cachix will provide self-hosting capabilities

**Comment by dsalaza4** [comment]
Reopening as:

- Attic is pretty mature now. Available via nixpkgs too
- Performance gain has to be reevaluated
- Cachix only provides self-hosting for enterprise plans

**Comment by dsalaza4** [comment]
Ended up using a different approach: https://gitlab.com/fluidattacks/universe/-/issues/12386#note_2002449349

Sticking to cachix + docker volumes for now.
