### ISSUE TITLE
Update makes to be fully runnable in macOS

### ISSUE THREAD

**Issue by jpverde** [fluidattacks/makes#1045]
There are some modules/args which are made to not be runnable in macOS.

This is an example that can be updated:
https://github.com/fluidattacks/makes/blob/1960239a7ab2e870ae3ad39f6ea2b307966bc972/src/args/make-node-js-modules/default.nix#L20

This line is not necessary since the job can be executed using macOs.

**Comment by dsalaza4** [comment]
@jpverde What are we missing here?

**Comment by jpverde** [comment]
> 

We can close this issue, as of today I haven't found any problems running makes after the updates.
