### ISSUE TITLE
`nix-linter` package is broken

### ISSUE THREAD

**Issue by jpverde** [fluidattacks/makes#1055]
`nix-linter` package is marked as broken in `nixpkgs` making `lintNix` broken.
This package is also not being actively maintained, lets consider changing it to a modern linter like [statix](https://github.com/NerdyPepper/statix)

**Comment by dsalaza4** [comment]
@jpverde Is this done?

**Comment by dsalaza4** [comment]
- [ ] Automatically fix before failing
- [ ] Separate arg from module
- [ ] Update doc

**Comment by jpverde** [comment]
I think this is done.
