### ISSUE TITLE
Error when running multiple instances at once

### ISSUE THREAD

**Issue by dacevedo12** [fluidattacks/makes#1068]
When running multiple instances of makes in a short frame of time, some fail due to

```
error: could not lock config file /var/folders/some/route/.gitconfig: File exists

Failed with exit code 255
```

Looking at the code, it seems related to the `_add_safe_directory` function

This happens often when using tools like mprocs

**Comment by dacevedo12** [comment]
A retry is usually enough. Would it make sense to catch the error and retry it automatically or is there a path to avoid this lock issue in git?

**Comment by dsalaza4** [comment]
I haven't seen the git-related error lately. Let's focus on retrying to create the temporary folder used by makes.

**Comment by dsalaza4** [comment]
Resolved in https://github.com/fluidattacks/makes/pull/1165/files
