### ISSUE TITLE
Add ruff linter

### ISSUE THREAD

**Issue by JchavesM** [fluidattacks/makes#1082]
Considering how fast it is, we should support [ruff](https://github.com/charliermarsh/ruff) within makes' python linters.

### Relevant links
[/lintPython settings](https://github.com/fluidattacks/makes/tree/main/src/evaluator/modules/lint-python)
[Prospector settings](https://github.com/fluidattacks/makes/blob/main/src/evaluator/modules/lint-python/settings-prospector.yaml)
[Issue to add ruff to prospector](https://github.com/PyCQA/prospector/issues/601)

**Comment by dacevedo12** [comment]
https://github.com/prospector-dev/prospector/pull/694 was just merged

**Comment by dsalaza4** [comment]
I am thinking about stopping support for most builtins. I would rather moving the `lintPython` logic to universe and handling it from there.
