### ISSUE TITLE
Add cython and numpy to envDownloads on makePythonPypiEnvironment

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#1083]
Although cython and numpy get bootstrapped to the environment https://github.com/fluidattacks/makes/blob/main/src/args/make-python-pypi-environment/default.nix#L47

It seems like they are not being downloaded from pypi-mirror https://github.com/fluidattacks/makes/blob/main/src/args/make-python-pypi-environment/default.nix#L96

This seems to make them impossible to find when needed.

**Comment by dsalaza4** [comment]
I will try adding them to `envDownloads` and see if they work properly.

@kamadorueda Any idea about why these two specific bootstrapped deps were not taken into account?

**Comment by kamadorueda** [comment]
I don't recall exactly at this point, but I do remember that bootstrapped and downloaded serve different purposes, and adding it to bootstrapped doesn't mean it's going to be available for download. The reason why some dependencies need to be bootstrapped is that pip expects them to be in the build environment (wheel, setuptools are common ones), if it should be available for download it should be added separately to the sources YAML of the project using Makes, or to this list (if in all projects it should be made available for download): https://github.com/fluidattacks/makes/blob/021d05fea30a6b95966ef0b5b2a0b6dfb24e50da/src/args/make-python-pypi-environment/default.nix#L112

**Comment by dsalaza4** [comment]
Makes sense! I just opened a PR adding cython to the downloaded sources when the flag is true as I recently found an error where it failed due to not being able to find it even when bootstrapped.
