### ISSUE TITLE
Enable custom rulesets for the lintMarkdown builtin

### ISSUE THREAD

**Issue by eytobo** [fluidattacks/makes#1087]
- [ ] Add a new parameter `--rulesets <ruleset path>` to the lintMarkdown linter implementation, which allows passing the file with [custom rules](https://github.com/markdownlint/markdownlint/blob/main/docs/creating_rules.md) for Markdownlint.

**Comment by dsalaza4** [comment]
@eytobo Is this done?

**Comment by elverytr** [comment]
Yes, it's done. I didn't close the issue because I couldn't find an option for it.

**Comment by elverytr** [comment]
> @eytobo Is this done?
Yes, it's done. I didn't close the issue because I couldn't find an option for it.
