### ISSUE TITLE
Error: "Semver match 3.19.0 to <2.15.1 || >=3.0a1 <3.0.0b9"

### ISSUE THREAD

**Issue by lesiki** [fluidattacks/makes#1090]
I'm getting `[ERROR] Semver match 3.19.0 to <2.15.1 || >=3.0a1 <3.0.0b9` after analysing paths.

![Screenshot 2023-05-15 at 12 55 59](https://github.com/fluidattacks/makes/assets/1673588/59061482-e32b-4b85-8153-db376bc0f7be)

The process then seems to freeze - no further logging beyond this. I've tried leaving it for up to 1 hour.

I'm not sure how to interpret this - is there a dependency in my python project with a versioning scheme that confuses the system or doesn't match some requirement? How do I find out which one?

**Comment by nate-penner** [comment]
I am experiencing a similar problem where it freezes. I do not have this error message, but on a certain project, it hangs after analyzing the last path, whereas on two other projects it works fine. I am running the casa scan docker container.
