### ISSUE TITLE
Licensing builtin with reuse

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#1099]
Let's create a `testLicense` builtin with reuse.

We already have a custom job for it: https://github.com/fluidattacks/makes/tree/main/makes/license

**Comment by dsalaza4** [comment]
@rohaquinlop,

I am reopening this issue as I just discovered a bug:

1. Remove all `testLicense` references within the repository.
2. Run `m .`
3. You will still see a `/testlicense` job.

This should not be the case, as outputs should only be created when a `testLicense` is declare within the makes.nix file

**Comment by rohaquinlop** [comment]
Got it! @dsalaza4
