### ISSUE TITLE
error: attribute 'attrPaths' missing

### ISSUE THREAD

**Issue by diman24** [fluidattacks/makes#1104]
Hi,
When following these instructions https://appdefensealliance.dev/casa/tier-2/ast-guide/static-scan I am getting this error while running "docker run casascan m gitlab:fluidattacks/universe@trunk /skims scan test/config.yaml" :

                                    🦄 Makes                                    
                                  v22.09-linux                                  

───────────────── Fetching gitlab:fluidattacks/universe@trunk ──────────────────

Initialized empty Git repository in /tmp/makes-24slmoms/.git/
From gitlab:fluidattacks/universe@trunk
From https://gitlab.com/fluidattacks/universe
 * [new branch]      trunk      -> trunk
Switched to branch 'trunk'

──────────────────────── Building project configuration ────────────────────────

copying path '/nix/store/v4alr5pcln6h03406f3s9hd89jkfl13y-source' from 'https://cache.nixos.org'...
error: attribute 'attrPaths' missing

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:507:28:

          506|         builtins.addErrorContext (context name)
          507|           (args.${name} or config._module.args.${name})
             |                            ^
          508|       ) (lib.functionArgs f);

       … while evaluating the module argument `attrPaths' in "/nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/evaluator/modules/default.nix":

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:505:44:

          504|       context = name: ''while evaluating the module argument `${name}' in "${key}":'';
          505|       extraArgs = builtins.mapAttrs (name: _:
             |                                            ^
          506|         builtins.addErrorContext (context name)

       … from call site

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:596:44:

          595|       defnsByName' = byName "config" (module: value:
          596|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          597|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:843:25:

          842|   */
          843|   dischargeProperties = def:
             |                         ^
          844|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:772:137:

          771|         defs' = concatMap (m:
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          773|         ) defs;

       … while evaluating definitions from `/nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/evaluator/modules/default.nix':

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:28:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                            ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:17:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                 ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:884:7:

          883|     in {
          884|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          885|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:785:9:

          784|       in {
          785|         values = defs''';
             |         ^
          786|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:791:5:

          790|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          791|     mergedValue =
             |     ^
          792|       if isDefined then

       … while evaluating the option `outputs':

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:756:9:

          755|     in warnDeprecation opt //
          756|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          757|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:274:72:

          273|           # For definitions that have an associated option
          274|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          275|

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:526:60:

          525|           # Push down position info.
          526|           (map (def: mapAttrs (n: v: { inherit (def) file; value = v; }) def.value) defs)));
             |                                                            ^
          527|       emptyValue = { value = {}; };

       … while evaluating 'dischargeProperties'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:843:25:

          842|   */
          843|   dischargeProperties = def:
             |                         ^
          844|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:772:137:

          771|         defs' = concatMap (m:
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          773|         ) defs;

       … while evaluating definitions from `/nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/evaluator/modules/default.nix':

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:28:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                            ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:17:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                 ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:884:7:

          883|     in {
          884|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          885|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:785:9:

          784|       in {
          785|         values = defs''';
             |         ^
          786|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:803:5:

          802|
          803|     optionalValue =
             |     ^
          804|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:522:86:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                                                      ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:522:51:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                   ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:306:62:

          305|     set:
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                                                              ^
          307|

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:306:29:

          305|     set:
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                             ^
          307|

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:306:18:

          305|     set:
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                  ^
          307|

       … while evaluating 'filterAttrs'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:305:5:

          304|     # The attribute set to filter
          305|     set:
             |     ^
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:522:35:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                   ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … while evaluating 'merge'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:521:20:

          520|       check = isAttrs;
          521|       merge = loc: defs:
             |                    ^
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:793:59:

          792|       if isDefined then
          793|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          794|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:791:5:

          790|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          791|     mergedValue =
             |     ^
          792|       if isDefined then

       … while evaluating the option `config':

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:756:9:

          755|     in warnDeprecation opt //
          756|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          757|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:274:72:

          273|           # For definitions that have an associated option
          274|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          275|

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/args/make-derivation/default.nix:27:9:

           26|     builtins.mapAttrs
           27|     (k: v: (
             |         ^
           28|       if (hasPrefix "__" k) || (hasPrefix "env" k)

       … from call site

       … while evaluating the attribute 'envAll' of the derivation 'config.json'

       at /nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/args/make-derivation/default.nix:92:7:

           91|       builder = "${__nixpkgs__.bash}/bin/bash";
           92|       name = toDerivationName name;
             |       ^
           93|       outputs = ["out"];

────────────────────────── 👾 Failed with exit code 1 ──────────────────────────

I suppose it should not matter much but I tried this same process on both MacOS Ventura and Windows 11 and got the exact same result.  Also, a shot in the dark, but it looks like it might not even have to do with the actual code that I am trying to test since I get the same error when omitting the path to config.yaml, like this: "docker run casascan m gitlab:fluidattacks/universe@trunk /skims scan"

What do you guys think?  I can't wrap my head around what might cause it ((

**Comment by dsalaza4** [comment]
Hi @diman24,

Please refer to this issue for more information: https://gitlab.com/fluidattacks/universe/-/issues/9659

My advise here is to simply run the latest makes container like this:

`docker run ghcr.io/fluidattacks/makes/amd64:latest m gitlab:fluidattacks/universe@trunk /skims scan` while standing in the root of the repo you want to scan.

Keep in mind we support containers for both `amd64` and `arm64`.

**Comment by diman24** [comment]
Thank you very much Daniel!  Your suggested approach worked.
