### ISSUE TITLE
[ERROR] The "path" configuration key was renamed. Please use "sast" instead.

### ISSUE THREAD

**Issue by chanx2** [fluidattacks/makes#1105]
I got two ERROR messages but the result shows success, do I need to worry about the ERROR?

[ERROR] The "path" configuration key was renamed. Please use "sast" instead.
[INFO] Official Documentation: https://docs.fluidattacks.com/machine/scanner/standalone/
[INFO] Namespace: OWASP
[ERROR] Computing commit hash:  
[INFO] info HEAD is now at: 0000000000000000000000000000000000000000
[INFO] Startup work dir is: /usr/scan
[INFO] Moving work dir to: /usr/scan
[INFO] An output file has been written: /usr/scan/Fluid-Attacks-Results.csv
[INFO] Summary: No vulnerabilities were found in your targets.

───────────────────────────────── 🏄 Success! ──────────────────────────────────

**Comment by jgomezb11** [comment]
Here is the official documentation of our tool: https://docs.fluidattacks.com/machine/scanner/standalone

If you are trying to achieve Tier 2 CASA compliance, I recommend reading this section: https://docs.fluidattacks.com/machine/scanner/standalone/casa
