### ISSUE TITLE
Document contributing for newcomers

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#1108]
Our [contributing page](https://makes.fluidattacks.com/contributing/) can use some improvements for newcomers:

- [ ] How to run your local changes (`git add` for Makes to interpret new files)
- [ ] Adding yourself to the mailmap
- [ ] Valid commit message
- [ ] DCO
- [ ] Adding and rendering documentation (`m . /docs/dev`)

Anything else you might find important to include.

Let's try to make this as simple and direct as possible, action-oriented.

**Comment by rohaquinlop** [comment]
Can you please assign it to me?
