### ISSUE TITLE
Operation not permitted when running RUN nix-env -if https://github.com/fluidattacks/makes/archive/22.09.tar.gz on Mac

### ISSUE THREAD

**Issue by yusjacobs** [fluidattacks/makes#1110]
### Dockerfile:

FROM nixos/nix:latest
WORKDIR /usr/scan
COPY . /usr/scan/
RUN mkdir results
RUN nix-env -if https://github.com/fluidattacks/makes/archive/22.09.tar.gz

### Error:
error: Operation not permitted
The command '/bin/sh -c nix-env -if https://github.com/fluidattacks/makes/archive/22.09.tar.gz' returned a non-zero code: 1

**Comment by jgomezb11** [comment]
Hello, I see that you are trying to complete Tier 2 of CASA for your application. I recommend reading this documentation that we have prepared specifically for your case: https://docs.fluidattacks.com/machine/scanner/standalone/casa. Please let me know if this helps you meet your needs.

**Comment by yusjacobs** [comment]
Thank you!

**Comment by yusjacobs** [comment]
Im following the steps described in the docs and get this when running the command to execute the scan:

🦄 Makes                                    
                                  v23.06-linux                                  

───────────────── Fetching gitlab:fluidattacks/universe@trunk ──────────────────

Initialized empty Git repository in /tmp/makes-crfgmryn/.git/
From gitlab:fluidattacks/universe@trunk
fatal: unable to access 'https://gitlab.com/fluidattacks/universe.git/': getaddrinfo() thread failed to start

───────────────────────── 😈 Failed with exit code 128 ─────────────────────────

**Comment by yusjacobs** [comment]
Hi. I was able to pull the docker image. After creating my local folder i ran:

$ docker run -v <path_to_local_folder>:/working-dir ghcr.io/fluidattacks/makes/amd64 m gitlab:fluidattacks/universe@trunk /skims scan ./config.yaml

with the corresponding path_to_local_folder. I got this error:

🦄 Makes                                    
                                  v23.06-linux                                  

───────────────── Fetching gitlab:fluidattacks/universe@trunk ──────────────────

Initialized empty Git repository in /tmp/makes-crfgmryn/.git/
From gitlab:fluidattacks/universe@trunk
fatal: unable to access 'https://gitlab.com/fluidattacks/universe.git/': getaddrinfo() thread failed to start

───────────────────────── 😈 Failed with exit code 128 ─────────────────────────

Am i doing something wrong?

**Comment by dsalaza4** [comment]
Hi @yusjacobs,

This is my first time seeing this error.

Maybe it has to do with your firewall? https://stackoverflow.com/a/61283733
