### ISSUE TITLE
error: attribute 'attrPaths' missing - Trying to run CASA Docker image for Fluid Attacks SAST

### ISSUE THREAD

**Issue by jr-johnson** [fluidattacks/makes#1114]
Hello,

I am receiving the below build error when trying to run the Fluid Attacks docker image for static analysis provided when going through the CASA self-assessment process. This command was working correctly about a week ago, but when I came back to re-scan my code base, it was broken. I've tried completely rebuilding the environment, clearing docker/cache completely, but I can't seem to get past this error. Please let me know if I can provide further information or if there's a better place to ask this question, thanks in advance!

----------------------------------------------------

docker run casascan m gitlab:fluidattacks/universe@trunk /skims scan config.yaml

                                    🦄 Makes                                    
                                  v22.09-linux                                  

───────────────── Fetching gitlab:fluidattacks/universe@trunk ──────────────────

Initialized empty Git repository in /tmp/makes-lcn2ciwa/.git/
From gitlab:fluidattacks/universe@trunk
From https://gitlab.com/fluidattacks/universe
 * [new branch]      trunk      -> trunk
Switched to branch 'trunk'

──────────────────────── Building project configuration ────────────────────────

copying path '/nix/store/7n67sxgrwchfjpwjady8rlmp350jzi3n-glibc-locales-2.37-8' from 'https://cache.nixos.org'...
copying path '/nix/store/88f2m3n8x4q5f59wnk1jsv987glhc19q-mirrors-list' from 'https://cache.nixos.org'...
copying path '/nix/store/czpf9rj96201q5zxllp3crhncs616a9i-curl-8.0.1-man' from 'https://cache.nixos.org'...
copying path '/nix/store/s9jvqjnzm6rmkzjr05fqda5ivd0dwkfk-nghttp2-1.51.0' from 'https://cache.nixos.org'...
copying path '/nix/store/jrid72i6ii9wx2ia6fyr2b1plri2m07l-libunistring-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/5w5qpm9z3iyib615pdih6nvk9spv3jbv-gcc-12.2.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/n4rypx4b99l6bh6ypgda5dm552axxfjh-nghttp2-1.51.0-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/wv33zvn4m0j6qlipy5ybfrixgipnfnyj-xgcc-12.2.0-libgcc' from 'https://cache.nixos.org'...
copying path '/nix/store/y382xj6bh8h4mmm22sw1a6q81rijrxl7-libidn2-2.3.4' from 'https://cache.nixos.org'...
copying path '/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8' from 'https://cache.nixos.org'...
copying path '/nix/store/qgjrd7fj77877x1w3qg0d619cqqd8wm8-attr-2.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/zlf0f88vj30sc7567b80l52d19pbdmy2-bash-5.2-p15' from 'https://cache.nixos.org'...
copying path '/nix/store/hyh6hg6rzm77rs4nix61nfwnxx2aqn40-ed-1.19' from 'https://cache.nixos.org'...
copying path '/nix/store/by4gv37sharnf370ki60zam5s7qklqqh-bzip2-1.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/4rwqxm67y0zkbxjg14zl9fdxf30cpgvy-gawk-5.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/gz0kx5v2asvlbf7gzr4v24h7dpza70zf-bzip2-1.0.8-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/g012c53brxmb0if3lpmkjwmxk74hjflh-gcc-12.2.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/ddygk5wqzmz69yqirrpcby2a28fam4g1-acl-2.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/vg9f8pmd2g0x3gb53nxwkw3yxizl3jpk-gnumake-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/93z4n7zy5hwpn06279jlmak75jmq1db1-gnused-4.9' from 'https://cache.nixos.org'...
copying path '/nix/store/2nprqmdmjmy5i2sii7j21fznmkwimqcr-gzip-1.12' from 'https://cache.nixos.org'...
copying path '/nix/store/lcfhnr6wrj9ssd3dxs39sprvz6qrxlj5-gnutar-1.34' from 'https://cache.nixos.org'...
copying path '/nix/store/r61yrb6y4g6hzfsk1bw9p0pjbb643bsz-keyutils-1.6.3-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/wy0incigsdz3nai26lxmn9ibchnb0qd6-libxcrypt-4.4.33' from 'https://cache.nixos.org'...
copying path '/nix/store/gnpwl8rdn5grp1szayhzla8bjs0cd9kn-nghttp2-1.51.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/hsxi3i3g1s4nbki271c33kn5agjpy6xm-libkrb5-1.20.1' from 'https://cache.nixos.org'...
copying path '/nix/store/nswapjr41vpsv8wfbvfxa4hdmyb4ihfy-openssl-3.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/kdgk1mgka2xd4rkmnfmcv3k2gm9jid6n-gmp-with-cxx-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/9gygdf93ik2i1j84wvcvvbkcn30nd4fd-nghttp2-1.51.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/swf1dckghdx7nza1lxz6s462pafwd7wa-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/2y0q33dmn7846bpqcnfch4a0q2q6dmya-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/zy7zq56cghkmcxd40gnhrciarm0hy5nw-libkrb5-1.20.1-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/arbxkmcgv9h8pjgj95c6d7r86yb77rl5-coreutils-9.1' from 'https://cache.nixos.org'...
copying path '/nix/store/nja07wpjdb6lyghi4izc30psw7j2kwxd-pcre-8.45' from 'https://cache.nixos.org'...
copying path '/nix/store/dg902ynzngjhzma49wsh9cdzckwf4y89-unzip-6.0' from 'https://cache.nixos.org'...
copying path '/nix/store/5533i5qzsxysjf38p1nlza9g9wvh09wk-xz-5.4.2' from 'https://cache.nixos.org'...
copying path '/nix/store/c01b2gmx1fjjkpnvj6bxy9q49g8qkpka-gnugrep-3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/2ldgh1qis9p4zf8bgsdm7897gw8vv36g-zlib-1.2.13' from 'https://cache.nixos.org'...
copying path '/nix/store/q951w69v8kbdrw6shdpibnl594yfr0by-diffutils-3.9' from 'https://cache.nixos.org'...
copying path '/nix/store/j5wraaxv16fcl10x11566a3807nr4nlr-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/0xpv4lac3ybc6hm9gg7ywkdazs4vsj8l-file-5.44' from 'https://cache.nixos.org'...
copying path '/nix/store/iyi02yc54n13d3gkbs7gv321k4h4s8j7-libssh2-1.10.0' from 'https://cache.nixos.org'...
copying path '/nix/store/m6kc0wg6zii4bcw0fqxmclgy27ph09va-perl-5.36.0' from 'https://cache.nixos.org'...
copying path '/nix/store/z5818pmhspx5772s4cp6ckhwhbin2f09-xz-5.4.2-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/hyknrzh8icblnj9zjjdlwkvdwbnlrm9r-curl-8.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/pyg9990n4ikqyvibj2cpl8i6hgywqjhw-libssh2-1.10.0-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/lf6arf2qj94qs6bkzfl2y75chb7awmx9-zlib-1.2.13-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/2lbb806yxr234n9b8hvj1cnzar55xkbq-curl-8.0.1-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/r1s2ahnl5cwcj1zrdsdfa0v8kch01gy7-openssl-3.0.8-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/lrf0sdjpgx56j09x0sgnd34mkczrbzna-openssl-3.0.8-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/9l2b851fyp1f2dvs4h7xfc0159s000nn-curl-8.0.1-dev' from 'https://cache.nixos.org'...
building '/nix/store/4ymhv0g60r7rpphasvg9isjjysxzlj1v-source.drv'...

trying https://github.com/nixos/nixpkgs/archive/d505646da5516457d258f88e76f02852e221bc03.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33.3M  100 33.3M    0     0  19.5M      0  0:00:01  0:00:01 --:--:-- 20.8M
unpacking source archive /tmp/nix-build-source.drv-0/d505646da5516457d258f88e76f02852e221bc03.tar.gz
error: attribute 'attrPaths' missing

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:507:28:

          506|         builtins.addErrorContext (context name)
          507|           (args.${name} or config._module.args.${name})
             |                            ^
          508|       ) (lib.functionArgs f);

       … while evaluating the module argument `attrPaths' in "/nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/evaluator/modules/default.nix":

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:505:44:

          504|       context = name: ''while evaluating the module argument `${name}' in "${key}":'';
          505|       extraArgs = builtins.mapAttrs (name: _:
             |                                            ^
          506|         builtins.addErrorContext (context name)

       … from call site

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:596:44:

          595|       defnsByName' = byName "config" (module: value:
          596|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          597|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:843:25:

          842|   */
          843|   dischargeProperties = def:
             |                         ^
          844|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:772:137:

          771|         defs' = concatMap (m:
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          773|         ) defs;

       … while evaluating definitions from `/nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/evaluator/modules/default.nix':

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:28:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                            ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:17:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                 ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:884:7:

          883|     in {
          884|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          885|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:785:9:

          784|       in {
          785|         values = defs''';
             |         ^
          786|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:791:5:

          790|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          791|     mergedValue =
             |     ^
          792|       if isDefined then

       … while evaluating the option `outputs':

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:756:9:

          755|     in warnDeprecation opt //
          756|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          757|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:274:72:

          273|           # For definitions that have an associated option
          274|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          275|

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:526:60:

          525|           # Push down position info.
          526|           (map (def: mapAttrs (n: v: { inherit (def) file; value = v; }) def.value) defs)));
             |                                                            ^
          527|       emptyValue = { value = {}; };

       … while evaluating 'dischargeProperties'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:843:25:

          842|   */
          843|   dischargeProperties = def:
             |                         ^
          844|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:772:137:

          771|         defs' = concatMap (m:
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          773|         ) defs;

       … while evaluating definitions from `/nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/evaluator/modules/default.nix':

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:28:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                            ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:771:17:

          770|         # Process mkMerge and mkIf properties.
          771|         defs' = concatMap (m:
             |                 ^
          772|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:884:7:

          883|     in {
          884|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          885|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:785:9:

          784|       in {
          785|         values = defs''';
             |         ^
          786|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:803:5:

          802|
          803|     optionalValue =
             |     ^
          804|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:522:86:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                                                      ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:522:51:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                                   ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:306:62:

          305|     set:
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                                                              ^
          307|

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:306:29:

          305|     set:
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                             ^
          307|

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:306:18:

          305|     set:
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));
             |                  ^
          307|

       … while evaluating 'filterAttrs'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:305:5:

          304|     # The attribute set to filter
          305|     set:
             |     ^
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:522:35:

          521|       merge = loc: defs:
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                                   ^
          523|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … while evaluating 'merge'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/types.nix:521:20:

          520|       check = isAttrs;
          521|       merge = loc: defs:
             |                    ^
          522|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:793:59:

          792|       if isDefined then
          793|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          794|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:791:5:

          790|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          791|     mergedValue =
             |     ^
          792|       if isDefined then

       … while evaluating the option `config':

       … while evaluating the attribute 'value'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:756:9:

          755|     in warnDeprecation opt //
          756|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          757|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/modules.nix:274:72:

          273|           # For definitions that have an associated option
          274|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          275|

       … from call site

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/j686cwms907knr9i90x8kq4587zmgmrg-nixpkgs-src/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/args/make-derivation/default.nix:27:9:

           26|     builtins.mapAttrs
           27|     (k: v: (
             |         ^
           28|       if (hasPrefix "__" k) || (hasPrefix "env" k)

       … from call site

       … while evaluating the attribute 'envAll' of the derivation 'config.json'

       at /nix/store/h0r02kl3yzml49x5470id43yk5dx512q-source/src/args/make-derivation/default.nix:92:7:

           91|       builder = "${__nixpkgs__.bash}/bin/bash";
           92|       name = toDerivationName name;
             |       ^
           93|       outputs = ["out"];

────────────────────────── 😈 Failed with exit code 1 ──────────────────────────

**Comment by jgomezb11** [comment]
Hello. I recommend reading this documentation that we have prepared specifically for your case: https://docs.fluidattacks.com/machine/scanner/standalone/casa. Please let me know if this helps you meet your needs.

**Comment by jr-johnson** [comment]
Thanks so much for the quick reply and the documentation, that was super helpful and did indeed fix my issues. I wish they would update the CASA website with this information!

**Comment by jeppeliisberg** [comment]
I'm getting the same error and the link provided not leads to a 404 page... seems it moved to https://docs.fluidattacks.com/tech/scanner/standalone/casa  - unfortunately, the instructions there only produced a new error.

**Comment by notmarshmllow** [comment]
Please repost the new link to the above mentioned page

**Comment by erik-lab** [comment]
Please repost the new link to the above mentioned documentation pages.

**Comment by jgomezb11** [comment]
https://help.fluidattacks.com/portal/en/kb/articles/validate-casa-tier-2-requirements#Run_the_scanner
