### ISSUE TITLE
makePythonPypiEnvironment and makePythonPyprojectPackage bridge

### ISSUE THREAD

**Issue by danmur97** [fluidattacks/makes#1161]
### Problem to solve
`makePythonPypiEnvironment` is a funtion that returns a `SourceAble` derivation rather than a `PythonPkgDerivation`.
This makes that they cannot be integrated together, forcing to rewrite `makePythonPypiEnvironment` dependencies on nix language.

### Intended users
Python developers
### Proposal
- Support a `PythonPkgDerivation` output for `makePythonPypiEnvironment` to enable integration with `makePythonPyprojectPackage`

### What does success look like, and how can we measure that?
`makePythonPypiEnvironment`
### Links / references

/label ~"type::feature"

**Comment by dsalaza4** [comment]
As discussed in #502, specific-purpose builtins will no longer be supported.
