### ISSUE TITLE
makePythonVscodeSettings

### ISSUE THREAD

**Issue by danmur97** [fluidattacks/makes#1168]
### Problem to solve
When entering a `direnv` environment is often necessary to adjust the path of the python interpreter to correctly setup vscode.

### Proposal
Add a util that sets the `.vscode/settings.json` to the specified python env.### Test plan

### Links / references

/label ~"type::feature"

**Comment by dsalaza4** [comment]
We want Makes to be core-lean, builtins will no longer be supported.
