### ISSUE TITLE
makePythonPoetryEnvironment

### ISSUE THREAD

**Issue by danmur97** [fluidattacks/makes#1171]
### Problem to solve
`makePythonPypiEnvironment` internally uses poetry to determine the full dependencies tree and outputs a source-able template and generates its own lock format.
But this brings some drawbacks:
- the dependencies format is transformed from poetry into a custom format https://github.com/fluidattacks/makes/issues/1149
- the output is incompatible with nix standard python env and pkgs derivations making difficult to integrate https://github.com/fluidattacks/makes/issues/1161
- pypi envs cannot be merged together into 1 python env. This causes that vscode settings util cannot be used to setup the full env plus brings some python env integration issues (same pkgs with diferent versions enabled)

### Intended users
Python developers
### Proposal
- Support `makePythonPoetryEnvironment` that receives a common poetry-lock (solving #1149) outputs a nix python env derivation (like `makePyprojectPackage`, and solving #1161 and env integration)
- try https://github.com/nix-community/poetry2nix
- this util will replace `makePythonPypiEnvironment`
### What does success look like, and how can we measure that?
`makePythonPypiEnvironment`
### Links / references

/label ~"type::feature"

**Comment by dsalaza4** [comment]
I will address making `makePythonPypiEnvironment` use poetry standard files on this issue

**Comment by jmesa85** [comment]
New builtin makePythonEnvironment generates an `error: home directory '/homeless-shelter' exists; please remove it to assure purity of builds without sandboxing` on jobs using the arch amd64.

https://us-east-1.console.aws.amazon.com/batch/home?region=us-east-1#jobs/ec2/detail/aa714a44-0ef6-4419-a082-070f76eaeac1

**Comment by dsalaza4** [comment]
@jmesa85 This is related to Nix not being able to run in sandbox mode on non-privileged containers
