### ISSUE TITLE
lintPython errors full report

### ISSUE THREAD

**Issue by juansedo** [fluidattacks/makes#1176]
## Problem

`lintPython` stops when mypy or prospector find any error. This behavior forces you to correct some errors and re-run the linter to find the others because **errors found by mypy are not the same as those found by prospector**.

## Proposal

Runs mypy and prospector always on `lintPython` running and print errors found by both.

**Comment by jrestrepoatfluid** [comment]
[scyth3-c](https://github.com/scyth3-c) there is the issue.

**Comment by dsalaza4** [comment]
lintPython will be deprecated soon.
