### ISSUE TITLE
Add new node.js version to makeNodeJsLock

### ISSUE THREAD

**Issue by friendglak** [fluidattacks/makes#1198]
### About issue

Currently, makeNodeJsLock only supports node_js_versions 14, 16, and 18. The new stable version of node.js is 20.10.0.

### Proposal

Add a  new LTS version of node.js version to makeNodeJsLock

**Comment by dsalaza4** [comment]
`makeNodeJsLock` now supports up to node 21: https://makes.fluidattacks.com/api/builtins/utilities/?h=makenodejs#makenodejslock
