### ISSUE TITLE
projectPath can't start with a dot

### ISSUE THREAD

**Issue by dacevedo12** [fluidattacks/makes#1200]
Since nix 2.19.0 store paths are not allowed to start with a dot.

![image](https://github.com/fluidattacks/makes/assets/29694570/d8f07af3-1ca9-4fc7-a41e-b7e241202466)

https://github.com/NixOS/nix/pull/9095

perhaps it could be escaped in the projectPath arg to avoid running into this error

**Comment by dsalaza4** [comment]
Still having issues. Decided to keep basenames and remove . prefixes.
