### ISSUE TITLE
Upgrade nixpkgs

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#1202]
It seems like the Nix version used when running the container is pretty old:

![image](https://github.com/fluidattacks/makes/assets/11205987/a5c5ea70-2671-4232-a8a4-65cf38ed9944)

We need to upgrade nixpkgs to the latest possible version to keep up to date with the latest nix versions.

**Comment by acuberosatfluid** [comment]
We ran into these errors in Universe after merging #1220 

https://gitlab.com/fluidattacks/universe/-/jobs/5765178089

We decided to revert the changes temporarily

**Comment by dsalaza4** [comment]
> @dsalaza4 @rohaquinlop
> 
> We ran into these errors in Universe after merging #1220
> 
> ```
> /tmp/nix-build-integrates-front-build.drv-0
> /nix/store/600g0if5farpw99rb6zbjgpswv4bb7j6-integrates-front-build/output/app
> error: home directory '/homeless-shelter' exists; please remove it to assure purity of builds without sandboxing
> ```
> 
> We decided to revert the changes temporarily, which fixed the pipelines

I think this is more related to `/integrates/front/build` needing to use the HOME directory in newer npm versions

**Comment by rohaquinlop** [comment]
`makeNodeJsLock` isn't working
![image](https://github.com/fluidattacks/makes/assets/50106623/e68b9573-68e0-4614-92ea-e83c8d1816e6)
