### ISSUE TITLE
Documentation on Github actions outdated

### ISSUE THREAD

**Issue by spacefrogg** [fluidattacks/makes#1328]
The documentation on how to set up the github actions to run makes are not up to date. When settings up as documented, the action fails with the job complaining about unsafe git directory permissions. I could fix the issue by inspecting the github actions used by this project, but, obviously, this error makes on-boarding new users difficult.

**Comment by rohaquinlop** [comment]
@spacefrogg thank you for reporting this, we just updated the documentation
