### ISSUE TITLE
Migrate to nixfmt

### ISSUE THREAD

**Issue by rohaquinlop** [fluidattacks/makes#1332]
[nixfmt](https://github.com/NixOS/nixfmt) will form the basis for the initial official standard Nix formatter, as established by [RFC 166](https://github.com/NixOS/rfcs/pull/166). We should migrate from `Alejandra` to `nixfmt`

**Comment by blotero** [comment]
`nixfmt` can only fail when the `check` flag is used, CI systems which rely on a job with this builtin would not fail under non compliant nix code. Is this intentional?
