### ISSUE TITLE
nix build sandbox on macOS

### ISSUE THREAD

**Issue by dacevedo12** [fluidattacks/makes#1354]
some large derivations (mainly the ones that build from node packages) exceed this limit when running on a sandbox https://github.com/NixOS/nix/issues/4119

even if the user disables sandbox mode at /etc/nix/nix.conf, the --option sandbox takes priority

https://github.com/fluidattacks/makes/blob/main/src/cli/main/cli.py#L291

current workaround is to `export MAKES_K8S_COMPAT=1` before running the command through makes

**Comment by dsalaza4** [comment]
I would rather getting rid of the sandbox option on the makes CLI and let users configure nix however they want on their nix.conf

**Comment by dsalaza4** [comment]
Sandboxing configurations were removed. Using sandbox or not is up to the user's nix.conf
