### ISSUE TITLE
Upgrade DynamoDB local version

### ISSUE THREAD

**Issue by juansedo** [fluidattacks/makes#1372]
## Context

Current supported version of DynamoDB local [is old](https://github.com/fluidattacks/makes/blob/main/src/args/make-dynamodb/default.nix#L15). Some features of new versions, like the *ReturnValuesOnConditionCheckFailure* feature, are missing due to this.

There's a [changelog](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocalHistory.html) about DynamoDB local versions to understand the implications and new features.

## Proposal

Consider to force the latest version by default and allow users to select the version of DynamoDB local.

**Comment by dsalaza4** [comment]
I would rather deprecating it altogether and simply move this logic to integrates itself.
