### ISSUE TITLE
Enable Independent Configuration for Each Module in lintTerraform

### ISSUE THREAD

**Issue by mandresuri** [fluidattacks/makes#1387]
Currently, the configuration setup in lintTerraform requires a shared, global configuration file that applies to all modules, which limits flexibility. This issue proposes a change to allow each module within lintTerraform to specify its own configuration file, removing the dependency on a shared configuration and enabling module-specific settings.

Tasks:

- Remove the need for a shared configuration file across all modules.
- Define an option for each module to specify its own configuration file, defaulting to a standard file if not provided.
- Update the function that processes modules to apply each module’s configuration independently.
- Test the setup to ensure each module can function with its own configuration file.
- Update documentation to reflect the behavior change, explaining the new module-specific configuration capabilities.

Acceptance Criteria:

- [ ] Each module within lintTerraform can specify its own independent configuration.
- [ ] Shared configuration dependency is removed.
- [ ] If no configuration is specified for a module, it defaults to a standard configuration file.
- [ ] Documentation clearly explains how to specify module-specific configurations, with examples if possible.

**Comment by dsalaza4** [comment]
We're currently trying to get rid of as many modules as we can. We need to move `lintTerraform` to Universe so we can support it from there.
