### ISSUE TITLE
Consider making src/modules/outputs/builtins/default.nix automatically detect new builtins

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#181]
For https://github.com/fluidattacks/makes/blob/main/src/modules/outputs/builtins/default.nix:

Is it possible to append the import of the `default.nix` from each builtin(subfolder) so we don't actually have to touch this file every time we add a new builtin?

**Comment by kamadorueda** [comment]
```nix
args:
let
  src = ./.;
  dirNames = builtins.attrNames (builtins.readDir src);  # Filter only directories so the default.nix does not load itself
in
{
  imports = builtins.map (name: import "${src}/${name}" args) dirNames;
}
```

**Comment by kamadorueda** [comment]
https://github.com/fluidattacks/makes/pull/186/files
