### ISSUE TITLE
Create a registry of Makes packages

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#188]
Currently you can do: `M_FROM=url-of-git-clone-of-a-project m` and list outputs from that remote git project

For user experience we shold shift that to the CLI, like `m url-of-git-clone-of-a-project`

Since writing the full url is long, we can create builtin aliases in makes, like: `m skims`. Internally makes would resolve skims to the product url, etc

The registry can be a JSON in the repo

**Comment by dsalaza4** [comment]
@kamadorueda Makes now forces providing a src path as first argument:

`m . /lintBash`.

I think we should not maintain json aliases, as anyone can easily:

1. Create aliases for daily use.
2. Add `args=()` for other automations.
