### ISSUE TITLE
Support for Lizard

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#234]
https://github.com/terryyin/lizard

Initially I'm adding support for:

--lenght Threshold for maximum function length warning. 
-- CCN Threshold for cyclomatic complexity number warning

**Comment by ludsrill** [comment]
@kamadorueda working on this one.

**Comment by ludsrill** [comment]
@kamadorueda should I use something like this?

 `python (enum [ "3.7" "3.8" "3.9" ]): Python interpreter version that your package/module is designed for.`

**Comment by kamadorueda** [comment]
You can use only the python version that benefits you more

**Comment by ludsrill** [comment]
Done.
