### ISSUE TITLE
Support for formatting and linting Nix

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#27]
Create formatNix (similar as formatBash),
and lintNix based on:  

https://gitlab.com/fluidattacks/product/-/tree/master/makes/applications/makes/lint

the mentioned URL is a single job that formats and lints at the same time, here in makes we want to have 2 modules: one for linting, one for formatting

add the required documentation

**Comment by dsalaza4** [comment]
@kamadorueda Working on this one.

**Comment by dsalaza4** [comment]
Done.
