### ISSUE TITLE
Support for linting bash

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#28]
Create lintBash (similar as formatBash) based on:

https://gitlab.com/fluidattacks/product/-/tree/master/makes/applications/makes/lint

the mentioned URL is a single job that formats and lints at the same time, here in makes we want to have 1 modules that lints only

add the required documentation

**Comment by dsalaza4** [comment]
@kamadorueda Working on this one

**Comment by dsalaza4** [comment]
Done in #106 and #127
