### ISSUE TITLE
Building related test at the same time

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#293]
I'm looking for a way to build all related test at the same time
for example, something like this 

```nix
lintWithLizard = {
  targets = {
    c = [ "pathfiles" ];
    py = [ "pathfiles" ];
    lobster  = [ "pathfiles" ];
  };
};
```
this going to produce outputs related by the name of the test

/lintWithLizard/c
/lintWithLizard/py
/lintWithLizard/lobster

The idea is to use makeScript to rerun **m .** from a bash file, get the names of the related tests and run them from bash.

Now respect to this, how could I add makes to my makeScript env?

if this a good approach? or should I try something different?

**Comment by kamadorueda** [comment]
defining what 'related' means is something you do manually

if all related outputs are derivations, you can use makeDerivationParallel

if all related outputs are  scripts and derivations, you can use makeScriptParallel to run in parallel the scripts, and add as dependency 1 makeDerivationParallell that links the derivations

You can install makes with:

makesSrc = fetchGithub { owner = fluidattacks, repo = makes, sha256 = ... }

searchPaths.bin = [ (import makesSrc) ]

but you can achieve what you want without using makes-inside-makes

**Comment by kamadorueda** [comment]
```nix
makeDerivation {
  dependencies = [
    outputs."/lintWithLizard/c"
    outputs."/buildC"
    outputs."/blablaForC"
  ];
  name = "c";
}
