### ISSUE TITLE
makeDerivationParallel: Argument list too long

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#313]
I'm getting the following error after successfully build around of 1000 makeDerivations (those are all the derivations that need to be run )

```md
while setting up the build environment: executing '/nix/store/x0dcb2rxlzf32g0ddfkqqz1sfcyx4yay-bash-4.4-p23/bin/bash': Argument list too long
```
Apparently all the derivations were built since I got cache for the derivations, 
however I cannot find the origin of this problem since I can't identify the command and the arguments that generate the error (I need help with this). 
(Maybe the parallel derivation need as parameters all those nested derivations to generated the nix/store/...... ?)

The problem appears when "make-derivation-parallel" is being built, this is the function that evaluated all lazy functions that were built.

**Comment by kamadorueda** [comment]
makeDerivationParallel is implemented as:

```nix
makeDerivation {
  env = {
    envDependencies = dependencies;
  };
  builder = "echo $envDependencies > $out";
  name = "make-derivation-parallel-for-${name}";
}
```

the command evaluates to: `echo a b c d e ... > $out`

given linux has a limit for the number of arguments that can be passed to a syscall then you get `Argument list too long`

we can make something like `cat $depsFile > $out, which only needs 1 argument for N dependencies

**Comment by kamadorueda** [comment]
https://github.com/fluidattacks/makes/pull/315
