### ISSUE TITLE
enforce camelCase outputs

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#34]
depending on how you name folders on the makes/ folder, the outputs are going to look like-this, or likeThis, or whatever you name the directories.

for consistency with makes built-ins, we should translate directory names to camelCase: https://levelup.gitconnected.com/converting-a-string-to-camelcase-in-javascript-f88a646a22b4

so people can have directories like /makes/my-derivation/main.nix, but execute `m .myDerivation`

nix has no built-in, and nixpkgs does not have a function in lib.strings, so we should create our own in this function: https://github.com/fluidattacks/makes/blob/27b669a539c6be8caffbbfab23da07a8c87a1f13/src/modules/outputs/custom.nix#L16 (turn name into camelCase before appending to the list)

**Comment by kamadorueda** [comment]
example of the casing incoherence:

![image](https://user-images.githubusercontent.com/47480384/123841478-38f2c500-d8d5-11eb-9dda-2c0cdc1620dc.png)

**Comment by 0xt3j4s** [comment]
@kamadorueda I am interested in working on this issue. Can I work on it?

**Comment by kamadorueda** [comment]
> @kamadorueda I am interested in working on this issue. Can I work on it?

@dsalaza4 is the current maintainer

**Comment by 0xt3j4s** [comment]
Hi, @dsalaza4! Can I work on this issue?

**Comment by dsalaza4** [comment]
@0xt3j4s Sure! If you have any questions do not hesitate to ask!

**Comment by dsalaza4** [comment]
This is the relevant source code:

https://github.com/fluidattacks/makes/blob/main/src/evaluator/modules/default.nix#L91

**Comment by 0xt3j4s** [comment]
Hey @dsalaza4, in the description of the issue, it is given that I need to change the name to camelCase in [this](https://github.com/fluidattacks/makes/blob/27b669a539c6be8caffbbfab23da07a8c87a1f13/src/modules/outputs/custom.nix#L16) file.

While you had given a different source code that is quite similar to the one shown in the issue, though in a [another directory](https://github.com/fluidattacks/makes/blob/726a5218739295a71d9543683e5dac8014813860/src/evaluator/modules/default.nix#L91).

Can you confirm the name conversion to camelCase should be done in which directory or branch?

**Comment by dsalaza4** [comment]
@0xt3j4s As this issue was created years ago, the source code has changed significantly. The file mentioned initially no longer exists.

**Comment by 0xt3j4s** [comment]
Oh, Ok. I got it and will work accordingly.

**Comment by dsalaza4** [comment]
Not relevant to us right now. We will most likely favor allowing users give their jobs whatever name they want
