### ISSUE TITLE
Add environment variable for rPackages

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#372]
export R_LIBS_USER  /library,

 to support R libraries installed from nixpkgs

**Comment by ludsrill** [comment]
since it's possible use rWarpper to achieve this
``nix`
(inputs.nixpkgs.rWrapper.override { 
  packages = [ 
    inputs.nixpkgs.rPackages.lintr
   ]; 
})
```
I'm working in a **makeREnvironment**

**Comment by kamadorueda** [comment]
stale
