### ISSUE TITLE
Pure NPM packaging

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#449]
As we did for Python: https://github.com/fluidattacks/makes/issues/434

This is the last component between what we have and a future where sandbox and restrict-eval are enabled

**Comment by dsalaza4** [comment]
https://www.npmjs.com/package/npm-mirror

**Comment by kamadorueda** [comment]
Notes on why we walk node_modules manually to create the node_modules/.bin folder

I tried adding the bin metadata to the registry like this:

```

  collectBinaries = tarball:
    let
      packageJsonPath = makeDerivation {
        builder = ./builder-for-collect-binaries.sh;
        env.envTarball = tarball;
        name = "${tarball.name}-package.json";
        searchPaths.bin = [ __nixpkgs__.gnutar __nixpkgs__.gzip ];
      };
      packageJson = fromJsonFile packageJsonPath;
    in
    attrsGet packageJson "bin" { };
```

But then node_modules/.bin/xxx would be a regular file instead of a symlink, and relative modules would not be resolved correctly

The symlink works very well

**Comment by kamadorueda** [comment]
We've [migrated](https://gitlab.com/fluidattacks/product/-/issues/5268) all [Fluid Attacks](fluidattacks.com) to this now, which accounts for 2820 different npm packages, so I consider it covers pretty much every real life case

Future work includes:
- Making it work on MacOS
- Private registries fetchers: fontawesome
- Overridden impure packages mozjpeg
