### ISSUE TITLE
source filtering capacity

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#508]
I want you to suggest having a look at the source filtering capacity that comes with https://github.com/NixOS/nixpkgs/pull/112083 for making it available in `makes`.

I think it will be of good use especially for the linters & such.

/cc @roberth

**Comment by kamadorueda** [comment]
Yes, I think we can create nice file/folder pickers out of it,

The most complex case we've needed so far is picking all files with a given extension in a folder,

It's already embeded in the framework (projectPathsMatching).
We are missing docs though, thanks for pointing this out!

**Comment by blaggacao** [comment]
Here is another shoulder of a giant: https://github.com/numtide/nix-filter

**Comment by dsalaza4** [comment]
In order to be consistent with #502, we will focus on inviting users to either import the utilities they want to use from nixpkgs or github.
