### ISSUE TITLE
Should we collect usage data?

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#535]
@kamadorueda I was wondering if other widely used FOSS solutions implement some sort of data collection for insights. Things like:

1. Monthly/weekly/daily calls
2. Most used args
3. Projects using makes
4. Users using makes

This is probably a sensitive topic, that's why it'd be great to investigate about what others do.

**Comment by dsalaza4** [comment]
Informing and asking users to accept some sort of terms might also be necessary? Using 100% of makes and rejecting all data collection should still be possible.

**Comment by kamadorueda** [comment]
Yes, they do collect data, for example:
- https://code.visualstudio.com/docs/getstarted/telemetry
- https://docs.npmjs.com/policies/privacy#npm-collects-data-about-how-you-use-npm-software-and-registries

The most user respectful way is **not** collecting data at all (as we do today),

However for understanding the usage of Makes and building a better product we can use non-[personal-identifiable-information](https://www.dol.gov/general/ppii) like hash(whoami, uname,ip) to identify users

We can use https://mixpanel.com/ for this

**Comment by dsalaza4** [comment]
No relevant to us right now.
