### ISSUE TITLE
module definition error provenance

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#542]
```
A definition for option `outputs./' is not of type `package'. Definition values:
- In `/nix/store/nj2n...-source/src/evaluator/modules/default.nix'
```

This error message says just about nothing. We need to improve it, possibly by using `_file` module attribute.

**Comment by dsalaza4** [comment]
I think we can close this because evaluators will eventually cease to exist as specific-purpose builtins get removed. Feel free to open new issues if more poor errors show up
