### ISSUE TITLE
a single additional cache is not enough

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#545]
In my scenario, I got:
- nixos cache
- company cache
- project cache

**Comment by kamadorueda** [comment]
Having many read caches and one write cache would be really awesome,

I think with current arch this would be very simple to implement

**Comment by blaggacao** [comment]
In addition, hard-coding it to `cachix.org` might not be very legit. But maybe that can be solved via #546 as well (read: `nixConf` settings).

**Comment by blaggacao** [comment]
x-ref: https://github.com/input-output-hk/makes/commit/3cd7dc0ded3f3b7515193f1f07a1b062aa607879

**Comment by kamadorueda** [comment]
> x-ref: input-output-hk@3cd7dc0

Good news is that we will get to the point where you won't have to fork

I'll try to merge those features upstream so the entire ecosystem benefits from this feedback,
we are also needing this feature at Fluid Attacks

**Comment by kamadorueda** [comment]
@blaggacao your feedback would be very appreciated: https://github.com/fluidattacks/makes#cache

**Comment by blaggacao** [comment]
Ok, gotta schedule it for after lunch. :hourglass:

**Comment by dsalaza4** [comment]
@kamadorueda 

What do you think about making `readExtra` a map so we can name each cache, just for clarity.

```
    readExtra = {
      fluidattacks = {
        url = "https://example.com";
        pubKey = "example.example.org-1:123...";
      };
      fluidattacksBackup = {
        url = "https://example2.com";
        pubKey = "example2.example2.org-1:123...";
      };
      autonomicjump = {
        url = "https://example3.com";
        pubKey = "example3.example3.org-1:123...";
      };
    };
```

**Comment by kamadorueda** [comment]
> Also, Is priority being considered here?

caches priority is defined by the cache itself, for example: https://cache.nixos.org/nix-cache-info (40) and https://fluidattacks.cachix.org/nix-cache-info (41)

**Comment by kamadorueda** [comment]
> What do you think about making readExtra a map so we can name each cache, just for clarity.

That's nice, though we don't use that data so that's why I didn't include it, also, there are code comments if people feel the need of adding such information

> Also, is there a specific reason for not including all readAndWrite parameters within each cache declared in readExtra? that way we would only have:

yes, the reason is that we only support read+write on cachix, whereas read caches can be anything from cachix, to hydra, to S3 buckets, anything over HTTP

the read protocol is standardizes, whereas the write protocol is not
