### ISSUE TITLE
Command completion is a _must_ on large job trees.

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#548]
I only have 3 jobs and already getting nervous.

Is there  good python support for **dynamic** cli completion?

Go's `cobra` currently has the by far the best support for _dynamic_ completion, afaik.

-> https://github.com/spf13/cobra

**Comment by kamadorueda** [comment]
We currently have:
```bash
$ m gitlab:fluidattacks/product@master |& grep -P '^  /' | wc -l
387
```
and we are not nervous 🎉 

Auto-completion would be very nice,
but with Flakes we _might_ not need it? on Flakes nix itself is the CLI (at least for now): https://github.com/fluidattacks/makes/pull/549

**Comment by kamadorueda** [comment]
https://click.palletsprojects.com/en/7.x/bashcomplete/

**Comment by kamadorueda** [comment]
@blaggacao you may want to check the new Makes CLI, it can't get better command completion

once you update Makes, just run `$ m f` to try it out over a big project
![demo](https://user-images.githubusercontent.com/47480384/136824332-7b0ece50-e10f-4b64-aba3-d76fe84d3bd2.gif)
