### ISSUE TITLE
project-spaced state vs global state

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#553]
https://github.com/fluidattacks/makes/blob/e30e69031e5614b50941266547cb07c22fce31fa/src/args/make-script/template.sh#L25

- running a cardano node has currently a state or roughly 9GB. That state should probably be (optionally) global.
- two scripts that generate wallet addresses for testnet using the same (hypothetical) `makes` builtin function `makeCardanoWallet` for most purposes would be intended to be differentiated by repo.

I could imagine doing an optional global state, defaulting to repo state.

Still I would keep the first naming category being the script name and the second some project name:

```
    && STATE="${HOME_IMPURE}/.makes/state/__argName__/__argProjectName__" \
```

This would require giving each project a project name in `makes.nix`.

Unfortunately flakes are anonymous (in human readable terms):
```
nix-repl> self.sourceInfo.
self.sourceInfo.lastModified      self.sourceInfo.outPath           self.sourceInfo.shortRev
self.sourceInfo.lastModifiedDate  self.sourceInfo.rev               self.sourceInfo.submodules
self.sourceInfo.narHash           self.sourceInfo.revCount
```

**Comment by kamadorueda** [comment]
we could also store the state relative to the root of the project, so it is local, for example in a out/<job-name> folder, former (internal) versions of Makes did this

we've not really defined this interface and nothing uses it at this moment, so you are free to change it or propose the schema that you think is better

**Comment by blaggacao** [comment]
I think, at least, basing state off of `IMPURE_HOME` opens up the venue to slap that onto a persistent volume and have some (frameworkish nag at) `dev` - `prod` paritiy with regard to how state folder layout is supposed to be (matching the job name above all).

**Comment by blaggacao** [comment]
I think also a distinction between persisted and cleared is worthwhile.
