### ISSUE TITLE
Execution Id in a gitops world

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#555]
I'd like to beleive, that in a fully declarative gitops world, the randomness introduced by the execution id (e.g for state invalidation) in _reality_ is stepped and tied to the git commit.

I'd argue: any given git commit cannot invalidate state that was produced under that same git commit.

On the other hand, if state is deemed commit-sensible, then any other commit should invalidate such state.

Therefore,`makesExecutionId` can maybe be renamed to `makesCommitEpoch` and pegged to (in the case of flakes) `self.rev` or `invalid` (if not a git repo - wtf?!). In non-flakes usage, `m` could polyfill correspondingly.

**Comment by blaggacao** [comment]
In a large monorepo, though, state incalidation would maybe actually be dependent on a subset pf the repositorie's file paths, that is a hash over them.

That might be an insteresting venue for an alternative implememtation making use of a poor man's input hashing strategy.

**Comment by kamadorueda** [comment]
The initial use case for this is time dependent jobs, since in those cases the Nix cache will prevent you from getting different results each time you build,  which is awesome! but also not what the user needs in this case

**Comment by kamadorueda** [comment]
In general we should deprecate this because with #180 we should be able to workaround time-dependent jobs,

I'm creating #564 to address the problem
