### ISSUE TITLE
Mutable source with flakes

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#567]
```
cat << EOF > $makesInject/flake.nix
{
  outputs = { ... }: {
    makes.mutableSource = $mutSource;
  };
}
EOF
```

&rarr; `nix run --override-input makesInject $makesInject ...`

---

Projects would need special setup:
```nix
{
  inputs.makesInject.url = "github:divnix/blank";
}
```

**Comment by blaggacao** [comment]
some tweaks might be in order so not to invalidate _eval_ cache on each run...

that file could be persisted in `.makes/inject/<repo>/` for example. (requires a stable repo identity similar to global state vs local state)

**Comment by kamadorueda** [comment]
no longer necessary: https://github.com/fluidattacks/makes/commit/068a36c17e4691dc6d78a2b924acfc4a084f6cf5
