### ISSUE TITLE
Support for ruby gems environment

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#574]
Support for ruby gems environment

**Comment by kamadorueda** [comment]
@ludsrill 

All Fluid Attacks now runs on this, we don't use Ruby extensively (maybe 100-200 gems) but anyway the essential features for packaging any gem should be available now

- https://github.com/fluidattacks/makes#ruby
- https://github.com/fluidattacks/makes#makerubyversion
- https://github.com/fluidattacks/makes#makerubygemsinstall
- https://github.com/fluidattacks/makes#makerubygemsenvironment
- https://github.com/fluidattacks/makes#fetchrubygem
