### ISSUE TITLE
Select option widget

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#605]
since the following was a bit contrived to find, maybe we can add a simple select option widget for semi-interactive runbooks...

```

function select_iogo_job {
  local string=""
  info "Please select the nomad job(s) that you deployed with iogo"
  PS3="Please enter: "
  select opt in routing front back signer rabbit patroni Ok Abort; do
      case $REPLY in
          1 | 2 | 3 | 4 | 5 | 6)
              string="${string}-$opt"
              ;;
          7)
              break
              ;;
          8)
              info Aborting
              exit
              ;;
          *) echo "invalid node $REPLY";;
      esac
  done
  echo "$string"
}

```

Any ideas?

**Comment by kamadorueda** [comment]
We currently have these two
- https://github.com/fluidattacks/makes#tobasharray
- https://github.com/fluidattacks/makes#tobashmap
I suppose we can write a third that does something like this:

```nix
let
   mySelect = toBashSelect {
    prompt = "pick whatever you want";
    options = [ "routing" "front" ... ];
   };
in
{ ... }
```

```bash
source "${envMySelect}/template" local selected_options  # derivations
source __argMySelect__/template local selected_options  # templates

echo "${selected_options[@]}"  # routing front .., whatever the user selected during the prompt
```

break and abort are automatically injected

**Comment by kamadorueda** [comment]
also maybe toBashSelectMany, toBashSelectOne

**Comment by kamadorueda** [comment]
or toBashSelect and a few options like:
- allowMultipleAnswers ? bool
- allowRepeatedAnswers ? bool
- minimumSelections ? int

**Comment by blaggacao** [comment]
The last suggestion seems best! Great conceptualization, thanks! I was a bit struggling on this one and I figured this might be the point where users start asking for a proper scripting language. My hope is we can extend bash's reach just another bit for most devops use cases...

**Comment by blaggacao** [comment]
Actually any language has the same problem: you can't paste them 1-by-1 on any dev's cli.

That's probably the single biggest advantage with bash in this devops case...

**Comment by dsalaza4** [comment]
We want makes to become a CLI that autocompletes existing jobs within a repository (#989) for maximum dev experience. We're not planning to support interactive shells.
