### ISSUE TITLE
available fetchers are not ok

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#609]
fetchers on Nix are not perfect

- builtins.fetchgit, does not bootstrap git, so you have to install it on the target host (happened to me in the past, using nixpkgs.fetchgit was the solution)
- builtins.fetchurl, does fail on large downloads or unstable networks, the output might not be the hash you want from time to time, probably from wrongly handled retries or keep-alive packets, (happened to me in the past, using nixpkgs.fetchurl was the solution)
- nixpkgs.fetch* are not local, which means they end up in the binary cache (a CDN) instead of downloading from the main CDN directly, which causes extra lookups and therefore extra build time when multiplied by thousands of downloads (happened to us in the past, around 5-10 minutes lost just Nix checking if X is in cache Y)

so, let's explore what we can do to prevent the mentioned problems

**Comment by blaggacao** [comment]
also: `nix` itself _not_ parallelizing bin cache look-ups is _not_ ok. /cc @nrdxp

**Comment by nrdxp** [comment]
incidentally, I was just wondering the potential difficulty of injecting a tokio runtime so I could leverage its [select macro](https://docs.rs/tokio/1.12.0/tokio/macro.select.html) directly into the Nix binary :sweat_smile:

**Comment by dsalaza4** [comment]
As discussed in #502, we will remove most of our own fetchers and leave that complexity to nixpkgs itself.
