### ISSUE TITLE
slower when using `NIX_UNSTABLE`

### ISSUE THREAD

**Issue by nrdxp** [fluidattacks/makes#648]
Not really sure of the reason yet, as I can't seem to figure out how to call the identical nix command for debugging, but whenever I try to use makes with unstable nix and flakes a simple invocation of `m .` takes 5s or more. I could understand this the first time, but nix unstable has an eval cache so I'm not sure why this happens every time.

Also, the delay doesn't happen at all using regular stable Nix.

I do have: 
```nix
(makes.lib.flakes.evaluate { inherit inputs; system = "x86_64-linux"; }) // {}
```

At the beginning of flake outputs, and I even tried removing the `--impure` argument from the script to see if that could possibly help somehow, but it didn't.

**Comment by kamadorueda** [comment]
This is because on Nix stable we try to mimic Nix unstable behavior of copying the entire project into a temporary folder, so the working directory is as pristine and hermetic as possible (without those git-ignored files, git untracked files, etc, that introduce NAR fragility when doing ./path/to/dir)

https://github.com/fluidattacks/makes/blob/main/src/cli/main/__main__.py#L115

On Nix stable this has purity benefits at the expense of an extra startup time depending on how much it takes to git-clone the last commit on your repository

On Nix unstable, this is unnecessary because Nix does it for us. This means on Makes with NIX_UNSTABLE=1 data is being copied twice. The good news is that we could save this step conditionally if NIX_UNSTABLE=1, improving overall startup performance

**Comment by nrdxp** [comment]
Thanks for the thorough explanation, I'll see if I can track down that codepath if you don't get to it first :sweat_smile:

**Comment by nrdxp** [comment]
made a bit of progress, looks like the actual delay was worse than the perceived delay :laughing: 

So originally I was waiting 13s for a `m .`, but I got it down to 8s with just this diff:
```
       # Checkout repository HEAD into a temporary directory
       # This is nice for reproducibility and security,
       # files not in the HEAD commit are left out of the build inputs
  -    head: str = _clone_src(src)
  +    if NIX_STABLE:
  +      head: str = _clone_src(src)
  +    else:
  +      return src
  ```
  
  and it didn't seem to break anything. There is probably some uneccesary copying still happening somewhere else though :thinking:

**Comment by kamadorueda** [comment]
that's the only copy operation we do, the next bottleneck would be that we perform some builds serially:

1. A nix build to compute the available outputs of your project (/asdf, /fdsa, ...) `attrs = _get_attrs(src, head)`
1. A nix build to compute the cache configuration `cache: List[Dict[str, str]] = _get_cache(src, head)`
1. The nix build of the output (/asdf, for example) 
1. (if configured) A cachix push 
1. (if configured) In the case the previous step has a "post-build" action like `cat` or `exec` then  it's run

an optimization can be merging steps 1 and 2 into a single nix-build,

could you place an `import time` at the top of the file of `__main__.py`, and `print(time.time())` before the steps done by the CLI? please
this would allows us to "profile" what's really happening and know what to focus on

**Comment by kamadorueda** [comment]
```diff
diff --git a/src/cli/main/__main__.py b/src/cli/main/__main__.py
index df21b9b..83a2de1 100644
--- a/src/cli/main/__main__.py
+++ b/src/cli/main/__main__.py
@@ -321,6 +321,7 @@ def _run(
     capture_io: bool = True,
     stdin: Optional[bytes] = None,
 ) -> Tuple[int, bytes, bytes]:
+    print("begin", time(), args)
     with subprocess.Popen(
         args=args,
         cwd=cwd,
@@ -332,6 +333,8 @@ def _run(
     ) as process:
         out, err = process.communicate(stdin)
 
+    print("end", time(), args)
+
     return process.returncode, out, err
```

**Comment by nrdxp** [comment]
okay so it seems to boil down now to nix missing the eval cache somehow:
```
begin 1632943360.4184446 ['/nix/store/s5vqiigpx5zw5fzqvyifrrr36zrakbjf-nix-2.4pre20210802_47e96bb/bin/nix', '--experimental-features', 'flakes nix-command', 'build', '--option', 'cores', '0', '--option', 'narinfo-cache-negative-ttl', '1', '--option', 'narinfo-cache-positive-ttl', '1', '--option', 'max-jobs', 'auto', '--option', 'substituters', 'https://cache.nixos.org https://hydra.iohk.io', '--option', 'trusted-public-keys', 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= ', '--option', 'sandbox', 'true', '--out-link', '/tmp/nix-shell.o9YTSk/tmpzryk1_uq', '--show-trace', '.#__makes__."config:attrs"']
end 1632943371.4750173 ['/nix/store/s5vqiigpx5zw5fzqvyifrrr36zrakbjf-nix-2.4pre20210802_47e96bb/bin/nix', '--experimental-features', 'flakes nix-command', 'build', '--option', 'cores', '0', '--option', 'narinfo-cache-negative-ttl', '1', '--option', 'narinfo-cache-positive-ttl', '1', '--option', 'max-jobs', 'auto', '--option', 'substituters', 'https://cache.nixos.org https://hydra.iohk.io', '--option', 'trusted-public-keys', 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= ', '--option', 'sandbox', 'true', '--out-link', '/tmp/nix-shell.o9YTSk/tmpzryk1_uq', '--show-trace', '.#__makes__."config:attrs"']
```

If I just build that attribute manually with a `nix build .#__makes__."config:attrs"` it returns almost immediately. Somehow it misses the cache on the first run and so evals from scratch every time :thinking:

**Comment by kamadorueda** [comment]
@nrdxp sure, let's increase it (or remove it to use its default value)

**Comment by nrdxp** [comment]
okay I think I have a PR ready then. I'll open in a bit after a little testing

**Comment by kamadorueda** [comment]
could: `'--out-link', '/tmp/nix-shell.o9YTSk/tmpzryk1_uq'` or `'--show-trace'`,  be responsible for the eval cache bypass?

**Comment by nrdxp** [comment]
Actually I'm extremely confused now. So removing the ttl didn't actually help and the delay is still there. So to I figured that something must have changed the output hash or nix wouldn't try to rebuild anything in the first place so I looked and the derivation built by makes and the one built by manually invoking nix are exactly the same, so there is no situation where nix should try to build it again. I invoked the exact command makes invokes with all the same arguments and it _doesn't_ stall.

Actually after typing all that, I think I remember a PR in Nix that changed the behavior of substituter checking since the makes version of Nix unstable (08.02.2021) was cut. The only difference left now is the unstable nix version between the one I invoke on my system (09.22.2021) and that one, so I think it must be this:
https://github.com/NixOS/nix/pull/5109

**Comment by kamadorueda** [comment]
if it helps, we're also open to decouple this `__nixpkgs__.nixUnstable`:

https://github.com/fluidattacks/makes/blob/main/default.nix#L16

so we can freely update nix 2.4 to their latest and greatest commit

**Comment by nrdxp** [comment]
it didn't help, now I'm utterly baffled :sweat_smile:

**Comment by nrdxp** [comment]
do you know how I can make nix just spit out it's stdout during a build so I can see what it's doing exactly by adding an `-L` flag? If I try to capture the stdout after the fact it's empty for some reason.

**Comment by kamadorueda** [comment]
This shows the stdout and stderr of all performed nix builds

```diff
diff --git a/src/cli/main/__main__.py b/src/cli/main/__main__.py
index df21b9b..6579379 100644
--- a/src/cli/main/__main__.py
+++ b/src/cli/main/__main__.py
@@ -220,11 +220,13 @@ def _nix_build(
         *_if(NIX_STABLE, "--attr", attr),
         *["--option", "cores", "0"],
         *_if(not NIX_STABLE, "--impure"),
-        *["--option", "narinfo-cache-negative-ttl", "1"],
-        *["--option", "narinfo-cache-positive-ttl", "1"],
+        *_if(not NIX_STABLE, "--log-format", "raw"),
         *["--option", "max-jobs", "auto"],
+        *_if(not NIX_STABLE, "--print-build-logs"),
+        # *_if(not NIX_STABLE, "--rebuild"),
         *["--option", "substituters", substituters],
         *["--option", "trusted-public-keys", trusted_pub_keys],
+        *_if(not NIX_STABLE, "--verbose"),
         *["--option", "sandbox", "false" if K8S_COMPAT else "true"],
         *_if(out, "--out-link", out),
         *_if(not out, "--no-out-link"),
@@ -286,6 +288,7 @@ def _get_attrs(src: str, head: str) -> List[str]:
             head=head,
             out=out,
         ),
+        capture_io=False,
     )
     if code == 0:
         with open(out, encoding="utf-8") as file:
@@ -305,6 +308,7 @@ def _get_cache(src: str, head: str) -> List[Dict[str, str]]:
             head=head,
             out=out,
         ),
+        capture_io=False,
     )
 
     if code == 0:

```

this spits stdout/stderr of nix-builds to console stdout/stderr, which is basically logs for _get_attrs and _get_cache. The logs for the main nix-build are already being shown to the console. For some reason Nix anyways show the bar with progress even with --log-format raw

---

Something curious I'm seeing is that it is downloading every time the flake inputs

**Comment by nrdxp** [comment]
oh you know what, the eval cache is stored in the users home directory, doesn't makes overwrite `HOME`?

**Comment by kamadorueda** [comment]
Yeah! makes overwrites HOME! many programs store state (impurities) there

Really good catch 🎯

**Comment by kamadorueda** [comment]
This makes nix build see HOME pointing to the real home

```diff
diff --git a/default.nix b/default.nix
index 53f1784..04a03ac 100644
--- a/default.nix
+++ b/default.nix
@@ -16,6 +16,9 @@ makeScript {
     __argNixUnstable__ = __nixpkgs__.nixUnstable;
   };
   entrypoint = ''
+    echo HOME=$HOME
+    echo HOME_IMPURE=$HOME_IMPURE
+
     __MAKES_REGISTRY__=__argMakesSrc__/src/cli/main/registry.json \
     __MAKES_SRC__=__argMakesSrc__ \
     __NIX_STABLE__=__argNixStable__ \
diff --git a/src/cli/main/__main__.py b/src/cli/main/__main__.py
index df21b9b..aea259e 100644
--- a/src/cli/main/__main__.py
+++ b/src/cli/main/__main__.py
@@ -286,6 +286,7 @@ def _get_attrs(src: str, head: str) -> List[str]:
             head=head,
             out=out,
         ),
+        env=dict(HOME=environ["HOME_IMPURE"]),
     )
     if code == 0:
         with open(out, encoding="utf-8") as file:
@@ -305,6 +306,7 @@ def _get_cache(src: str, head: str) -> List[Dict[str, str]]:
             head=head,
             out=out,
         ),
+        env=dict(HOME=environ["HOME_IMPURE"]),
     )
 
     if code == 0:
@@ -413,6 +415,7 @@ def cli(args: List[str]) -> None:
             head=head,
             out=out,
         ),
+        env=dict(HOME=environ["HOME_IMPURE"]),
         capture_io=False,
     )
 
```

**Comment by kamadorueda** [comment]
I confirm that with HOME_IMPURE nixpkgs is not downloaded over and over

**Comment by kamadorueda** [comment]
This is also required so other env vars like PATH are propagated correctly:

```diff
diff --git a/src/cli/main/__main__.py b/src/cli/main/__main__.py
index df21b9b..f8fad58 100644
--- a/src/cli/main/__main__.py
+++ b/src/cli/main/__main__.py
@@ -321,10 +323,13 @@ def _run(
     capture_io: bool = True,
     stdin: Optional[bytes] = None,
 ) -> Tuple[int, bytes, bytes]:
+    final_env = environ.copy()
+    final_env = final_env.update(env or {})
+
     with subprocess.Popen(
         args=args,
         cwd=cwd,
-        env=env,
+        env=final_env,
         shell=False,  # nosec
         stdin=None if stdin is None else subprocess.PIPE,
         stdout=subprocess.PIPE if capture_io else None,
 ```

**Comment by nrdxp** [comment]
hmm, that last patch actually seems to reintroduce the delay
