### ISSUE TITLE
searchPath for ocaml pkgs

### ISSUE THREAD

**Issue by ludsrill** [fluidattacks/makes#650]
While trying to use Ocaml packages provided by **nixpkgs** I found that we need to export some environment variables, so I could add these environment variables to **searchPath** but these env vars are associated with an ocaml version folder which depends on **fetchNixpkgs**, for instance, nixpkgs stable: `lib/ocaml/4.12.0/site-lib`

Should I create something as **ocamlPath412**? or maybe, if it's possible, we could allow the use of globing in **searchPath** to use something like `lib/ocaml/*/site-lib` to keep **ocamlPath**

On the other hand, we could forget `ocamlPackages` and give support to the packages using **opam** as with ruby gems

**Comment by kamadorueda** [comment]
Does this allow you to do what you need?

```bash
$ cat -n makes/nested/main.nix 
     1	{ __nixpkgs__
     2	, makeSearchPaths
     3	, ...
     4	}:
     5	let
     6	  ocaml = __nixpkgs__.ocaml_4_03;
     7	  ocamlPackages = __nixpkgs__.ocamlPackages_4_03;
     8	in
     9	makeSearchPaths {
    10	  ocamlBin = [ ocamlPackages.wtf8 ];
    11	  ocamlLib = [ "${ocamlPackages.wtf8}/lib/ocaml/${ocaml.version}/site-lib" ];
    12	}



$ just m . /nested
"$(nix-build --show-trace --no-out-link)/bin/m" . /nested
Makes v21.10-linux

/nix/store/96nqnrdli3arypki129j81djkhgkvhdj-make-template-for-make-search-paths
export PATH="/nix/store/ixj4gm1ynjgh7bmfh5xk6hdkm5afnv6p-ocaml4.03.0-wtf8-1.0.2/bin${PATH:+:}${PATH:-}"
export OCAMLPATH="/nix/store/ixj4gm1ynjgh7bmfh5xk6hdkm5afnv6p-ocaml4.03.0-wtf8-1.0.2/lib/ocaml/4.03.0/site-lib${OCAMLPATH:+:}${OCAMLPATH:-}"
```

**Comment by ludsrill** [comment]
this works perfect, I'm adding an additional PATH with this syntax
