### ISSUE TITLE
Consider Pure Nix

### ISSUE THREAD

**Issue by nrdxp** [fluidattacks/makes#652]
I've by no means run a thorough code analysis of the project, but I haven't seen anything yet that would make pure evaluation completely impossible. It is feasible that Nix, perhaps after CA derivations stabilize, could make pure evaluation mandatory, so it may be worth considering now whether the core segments could be refactored to work interchangeably with Nix _Next_, let's say, and Nix Stable.

**Comment by kamadorueda** [comment]
It's convenience only, for instance we added --impure on nix-unstable feature flag just to avoid fighting too much with this: https://github.com/fluidattacks/makes/issues/585

But I totally agree with you. Currently we are:
- fully --option sandbox true
- but with restrict-eval false (--impure on nix unstable)
this is good enough with nix stable (as restrict eval as far as I know was created for hydra only), but definitely we should try to go all-in on restrict-eval true, for future releases on Nix

Thanks for pointing this out!

**Comment by dsalaza4** [comment]
As of now we're giving priority to cross-environment-reproducibility (containers, macos, linux, arm64) over purity. Once we start working on #989 the current state of nix will be evaluated and a decision regarding this will be made.
