### ISSUE TITLE
Jobs collecting too slow

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#664]
When running:

`$ m . /test + double_tab` within `product`, it takes several seconds for makes to actually be able to show the jobs. 

I am guessing this is not because of the filtering itself because running `m .` also takes around 5 seconds.

@kamadorueda Any thoughts regarding how we can optimize job discovery?

**Comment by dsalaza4** [comment]
```
product$ time m .

...
real    0m5,415s
user    0m4,289s
sys     0m1,023s
```

**Comment by kamadorueda** [comment]
In general this is the solution: https://github.com/fluidattacks/makes/milestone/1

and more specifically the optimizations discussed here: https://github.com/fluidattacks/makes/issues/648

another option is making the outputs list a constant like we did in previous versions of Makes: https://gitlab.com/fluidattacks/product/-/blob/23ab7b9181d382e100ff8c3ac33a4d48382865b4/makes/attrs/packages.lst
I just consider this to be too ugly UX, and explaining this to other people is more costly than just waiting 1 evaluation, which on Flakes would be pretty much a noop thanks to evaluation caching

**Comment by blaggacao** [comment]
@nrdxp & me are regularly discussing eval cache issues.

The outlook is that all _pure_ nix functions in flakes will be individually cached.

I'm not sure how far this has progressed, but afaik, currently the cached entity is the _entire_ flake.

We can think of eval caching like a _compiled_ version of a nix program.

Even further down, it would be a fun thing to replace the `sqlight` eval cache with a distributed `dqlight` drop-in. That way the _compiled_ version of a nix programm could be fetched from CI.

That should tremendously speed up things for all participants in a network.

_Music of the future._

**Comment by kamadorueda** [comment]
Another option in the short term is making the autocompletion script cache the list of outputs for let's say 30 seconds. This should work perfectly enough

**Comment by kamadorueda** [comment]
Bash completion and making jobs collection faster won't be necessary if we implement a TUI for picking the output at #714 

Closing to focus on that
