### ISSUE TITLE
Update prospector in lintPython

### ISSUE THREAD

**Issue by drestrepom** [fluidattacks/makes#672]
prospector integrates several tools, pylint is outdated and does not cover some cases

![image](https://user-images.githubusercontent.com/36453706/135653075-68167558-db53-4812-86a7-48ab3ab0a223.png)

with the most current version suppression is not required
![image](https://user-images.githubusercontent.com/36453706/135653437-9167c24d-9049-4bd5-95cb-5b0880697421.png)

**Comment by kamadorueda** [comment]
We could pin it here: https://github.com/fluidattacks/makes/blob/main/src/args/lint-python/pypi-deps.yaml so we can update pylint to its latest version separately from prospector
