### ISSUE TITLE
substituter prio nix2.4 rel notes

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#676]
> * The priority of substituters can now be overridden using the
  `priority` substituter setting (e.g. `--substituters
  'http://cache.nixos.org?priority=100 daemon?priority=10'`).

I remember a recent discussion in this space. FYI.

I don't know if we should log in any action into the backlog.

**Comment by blaggacao** [comment]
also, not related:

> * Plugins can now register `nix` subcommands.

**Comment by dsalaza4** [comment]
Will review in #989
