### ISSUE TITLE
Structure roadmap milestones and contributions

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#677]
Issues are getting numerous, some of them will be worked on anytime soon, while others may remain open and unassigned for a long time. Additionally, some issues are sponsored by organizations who dedicate full time developers to them given their strong interest and dependency in the project, and others who are community driven and whose resolution may vary depending on the availability of someone willing to work on it

In general after closing this issue I expect to structure and coordinate better the efforts of contributors by making evident the areas that require help, and also the areas that are currently being worked on (and their priority), while also letting end users know which is the direction that the project is taking (given the available resources), and kindly inviting people to contribute in order to make Makes a better FOSS project for all of us, and the new users to come!

**Comment by blaggacao** [comment]
I think you're already doing a decent job with the labels.
