### ISSUE TITLE
Kill processes listening on port

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#687]
For writting indempotent scripts it's a good idea to kill whatever is listening on the ports that the script is going to use, and to clean up used ports on-exit. This trivial task however requires some digging on the internet and CLI kung-fu. It would be nice to have them embedded into the framework as an argument

Example implementation:
- https://gitlab.com/fluidattacks/product/-/tree/708bb9d1662b8431c2439d540465c72167b9b719/makes/applications/makes/kill-port
- https://gitlab.com/fluidattacks/product/-/tree/708bb9d1662b8431c2439d540465c72167b9b719/makes/applications/makes/kill-tree

**Comment by dsalaza4** [comment]
related to #689
