### ISSUE TITLE
S3-like local web server

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#688]
Having a local web server that is S3-compatible is very nice for development. Having it embedded on Makes would be much appreciated and would allow other people to re-use it in their projects.

As a plus, adding options for populating buckets from existing S3 buckets can further save imperative code and turn it into declarative beauties 

Example implementation:
- https://gitlab.com/fluidattacks/product/-/tree/708bb9d1662b8431c2439d540465c72167b9b719/makes/applications/integrates/storage

**Comment by ludsrill** [comment]
I wanna work on this but its not totally clear for me, I would like to know the general functioning or objective of the example that you give us
