### ISSUE TITLE
Upload source maps to Bugsnag

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#691]
On transpiled, minified and optimize production Javascript bundles Bugnsag is not able to report the correct line of code where the exception happened. On this cases uploading source maps that maps optimized line of code to original human readable line of code is very appreciated

This script does that, so people can re-use:
- https://gitlab.com/fluidattacks/product/-/blob/708bb9d1662b8431c2439d540465c72167b9b719/makes/applications/makes/bugsnag/source-map-uploader/entrypoint.sh

**Comment by dsalaza4** [comment]
We're no longer interested in growing the number of Makes builtins.
