### ISSUE TITLE
[documentation] [first time user feedback] GitLab example did not work for me

### ISSUE THREAD

**Issue by ghost** [fluidattacks/makes#696]
👋 I love y'alls work on this project! 

CI rightly encompasses a number of concerns that frameworks could solve.

My problem is a specific example of #511. 

I found the blog post on makes from nixos.org.
I've manually GitLab nix based CI infrastructure so wanted to try this framework to see if it makes my life easier.

I followed the developer user [getting started.](https://github.com/fluidattacks/makes#getting-started).
My GitLab instance has a docker executor and I added this job to my `.gitlab-ci.yml`:
```
makes experiment:
  interruptible: true
  stage: test
  image: ghcr.io/fluidattacks/makes:main
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  script:
    - m . /helloWorld 1 2 3

```
My job executed and failed with:
<img width="816" alt="Screen Shot 2021-10-06 at 10 39 26 AM" src="https://user-images.githubusercontent.com/472721/136225675-d22591af-a8bc-45d6-8bc3-6b0b4b97beb6.png">

As an aside, the size and number of layers in `ghcr.io/fluidattacks/makes:main` surprised me as it seemed quite slow to use. If possible, I would recommend creating a nimbler example Docker image to appease picky developers like me.

**Comment by kamadorueda** [comment]
Hi, thanks for the feedback!

I have created an example for Gitlab: https://gitlab.com/fluidattacks/makes-example-1
gonna add it to the documentation soon

From the error message you show, it seems that you have not commited the `makes.nix` file to your repository. Once you do, it should work very well:

- https://gitlab.com/fluidattacks/makes-example-1/-/blob/main/.gitlab-ci.yml
- https://gitlab.com/fluidattacks/makes-example-1/-/blob/main/makes.nix
- https://gitlab.com/fluidattacks/makes-example-1/-/jobs/1655533261
- ![image](https://user-images.githubusercontent.com/47480384/136243778-cfe84f5f-697c-4116-8be1-7f5456f5ea9a.png)

Let me know if it worked

**Comment by kamadorueda** [comment]
You can also test the example like this: 
- ` $ m gitlab:fluidattacks/makes-example-1@main `
- ` $ m gitlab:fluidattacks/makes-example-1@main /helloWorld 1 2 3 4 `
