### ISSUE TITLE
Makes Secrets module

### ISSUE THREAD

**Issue by jrestrepoatfluid** [fluidattacks/makes#710]
**Problem to solve**

First:
Creating a sops encrypted file should be simple, let's create a terraform module for it,
so products can just invoke the module and voila! a sops key is possible

Second:
Having dev/prod keys is not enough for re-usability.
Today if we want to have creds for some service, then we have to:

- copy paste creds, which hurts maintainability
- use many product roles for 1 product, which hurts separation of concerns

**Proposal**

Abstract common code with terraform modules so we avoid this copy-paste
Once creating kms keys with terraform modules is simple, then let's have many sops files for common objects, for instance:

- sops file for redshift db creds
- sops file for X shared product

Then grant product users access to the individual sops files, for maximum access control and granularity

**Comment by dsalaza4** [comment]
As terraform infra handles a state, I figured this would be easier to implement by managing modules in our product repository that would allow to:

1. Create aws and cloudflare users
2. Create kms keys
3. Publish aws users to gitlab

All these features were implemented [here](https://gitlab.com/fluidattacks/product/-/tree/master/makes/foss/modules/makes/users/modules) and are being used across all our products.

Regarding simplifying sops secrets creation, `makeSopsEncryptedFile` utility has been created.
