### ISSUE TITLE
A nix type system shim

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#711]
If needed, this seems to be a shim-in-able type system for nix for functin signatures not as heavy as the module system:

https://code.tvl.fyi/tree/nix/yants

**Comment by dsalaza4** [comment]
I am not sure about the state of the module system on nixpkgs. I will close this for now and make sure to keep an eye on nix RFCs that try to improve nix type checking: https://www.haskellforall.com/2022/03/the-hard-part-of-type-checking-nix.html
