### ISSUE TITLE
Knowledge: dream2nix ("any2nix")

### ISSUE THREAD

**Issue by blaggacao** [fluidattacks/makes#721]
A friend just started this project (planning on) making use of RFC92 to avoid IFD for 2nix approaches.

My gut tells me that this is something makes could fully embrace for it's 2nix effort which heavily leans towards preserving native tooling so that it preserves familiarity for developers.

https://github.com/DavHau/dream2nix

The relevant status update on RFC92 which hinted to this project is https://github.com/NixOS/rfcs/pull/92#issuecomment-939203270

**Comment by dsalaza4** [comment]
In order to keep makes lean-core (#502), provisioning language-specific dependencies in a nixified way will no longer be supported. Users can directly import poetry2nix, node2nix, or whatever they want to use to their project.
