### ISSUE TITLE
Separate args from modules

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#735]
Some modules do not follow the arg/module architecture yet. Let's migrate them.

- [ ] lint-bash
- [ ] lint-nix
- [ ] format-javascript
- [ ] format-markdown
- [ ] format-nix
- [ ] format-python

**Comment by pratham-bhatnagar** [comment]
Can I work on this ? @dsalaza4

**Comment by dsalaza4** [comment]
As discussed in #502, modules will eventually cease to exist. This is no longer relevant.
