### ISSUE TITLE
Support `nixpkgsBuildInputs` in `makeSearchPaths`

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#739]
After trying to update to the latest commit of Nixpkgs I found some packages not to be self-contained via declarative setup code (normally a wrapper that expose a few env vars and then call the main code) but instead of `$out/nix-support` magic. This magic is normally triggered with a `$ source $stdenv/setup`)

Since here at Makes we don't use setup hooks because they are **anti-modular**,
as the [Nixpkgs documentation](https://nixos.org/manual/nixpkgs/stable/#ssec-setup-hooks) says:

![image](https://user-images.githubusercontent.com/47480384/136981546-fd17bb2e-fe5e-4fac-acd9-84e02865acac.png)

We can instead offer a small attribute `nixpkgsBuildInputs` in `makeSearchPaths` to expose a compatibility layer. This compatibility layer can be achieved as simple as this: 

```nix
{
   __envNixpkgsSrc = __nixpkgsSrc__;
   __envNixpkgsBuildInputs = [
     __nixpkgs__.gnugrep
     __nixpkgs__.python3Packages.chardet
     __nixpkgs__.rpl
   ];
   __envNixpkgsInitialPath = [ __nixpkgs__.coreutils ];
}
```

```bash
export buildInputs="${__envNixpkgsBuildInputs}"
export initialPath="${__envNixpkgsInitialPath}"
source "${__envNixpkgsSrc}/pkgs/stdenv/generic/setup.sh"
```

In the order of evaluation, nixpkgs should come first, then makes, so makes overrides nixpkgs

**Comment by dsalaza4** [comment]
We're considering deprecating `makeDerivation` in favor of `nixpkgs.mkDerivation`. We want to move that complexity back to nixpkgs and let them do their magical hooks.
