### ISSUE TITLE
Integrate --help with CLI

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#740]
Currently we handle help scripts like this:

You exec command --help:

![image](https://user-images.githubusercontent.com/47480384/137013544-557db98b-640c-4c2d-b81d-0a5998679f80.png)

then it runs and show:

![image](https://user-images.githubusercontent.com/47480384/137013525-d8fe07d7-12cf-4572-9596-f72e278bb677.png)

---

Now that we have an excellent CLI, 
instead of having a markdown help that is invoked in the script itself,
we can make it part of the CLI and render it once there is a full match for the output,
in the bottom panel:

![image](https://user-images.githubusercontent.com/47480384/137013686-41531c7d-e04a-4eec-a905-52b301b9bae4.png)

it would be faster, more dynamic, more accesible, auto-documented, and our CLI library already supports rendering markdown excellently

@blaggacao

**Comment by blaggacao** [comment]
> plus a flag for disabling adding such help to the CLI
`m .  /path/to/script -- --help`

This is how the esacpe hatch is currently implemented. It was the best design I could come up with.

In the context of `makes` tasks, `--help` might still have a different focus. For example it might be a use case specific instruction whereas `-- --help` might just be the general command help.

**Comment by dsalaza4** [comment]
Will review this in #989. Ideally:

1. A CLI instead of a TUI (calling `m . /job` directly)
2. Autocompletion for `/job` with tab
3. Documentation with `--help`
