### ISSUE TITLE
infinite recursion when using inputs

### ISSUE THREAD

**Issue by nrdxp** [fluidattacks/makes#742]
Mimimal reproduction flake:
https://github.com/nrdxp/repro

Infinite recursion occurs the moment one tries to access `inputs` from "makes.nix" in any fashion. It happens with both stable and unstable interface. To reproduce simply enter the flake's devshell and run `m .`.

**Comment by kamadorueda** [comment]
Interesting, and also seems simple, I'm gonna drop here examples that work and ones that do not work so you see the pattern

Works:
```nix
{ fetchNixpkgs, inputs, ... }:
{
  inputs = {
    nixpkgs = import <nixpkgs> { };
  };
  outputs = {
    "/hello" = inputs.nixpkgs.bash;
  };
}
```

Works:
```nix
{ fetchNixpkgs, inputs, ... }:
{
  inputs = {
    nixpkgs = import <nixpkgs> { };
  };
  outputs = {
    "/hello" = builtins.trace inputs inputs.nixpkgs.bash;
  };
}
```

Works:
```nix
{ fetchNixpkgs, inputs, ... }:
{
  inputs = {
    nixpkgs = import <nixpkgs> { };
  };
  outputs = builtins.trace inputs {
    "/hello" = inputs.nixpkgs.bash;
  };
}
```

Fails:
```nix
{ fetchNixpkgs, inputs, ... }:
{
  inputs = builtins.trace inputs {
    nixpkgs = import <nixpkgs> { };
  };
  outputs = {
    "/hello" = inputs.nixpkgs.bash;
  };
}
```

Fails:
```nix
{ fetchNixpkgs, inputs, ... }:
builtins.trace inputs {
  inputs = {
    nixpkgs = import <nixpkgs> { };
  };
  outputs = {
    "/hello" = inputs.nixpkgs.bash;
  };
}
```

Fails:
```nix
{ fetchNixpkgs, inputs, ... }:
{
  inputs = {
    nixpkgs = import <nixpkgs> { };
  };
  outputs = {
    "/hello" = inputs.nixpkgs.bash;
  };
  a = builtins.trace inputs inputs.nixkgs.bash;
}
```

inputs depends on evaluating the section of the module system that defines the inputs

if for evaluating the inputs section of the module system you somehow need the inputs, it fails.

since `a` is not part of the module system, then inputs can't be evaluated, and nixpkgs.lib.modules.evalModules tries to eval the inputs while displaying the error message, which depends on evaluating the module in the first place

**Comment by kamadorueda** [comment]
there is not much we can do about the specific case you mention:

```nix
{ inputs, ... }:
{
  foo = inputs;
}
```

it fails even if you did not use inputs at all:

```
{ inputs, ... }:
{
  foo = 123;
}
# The option `foo' does not exist. Definition values:
# - In `<unknown-file>': 123
```

the infinite recursion is born after a failure in the first place,
so just remove the original failure (option foo does not exist) and it'll work as expected

**Comment by blaggacao** [comment]
> the infinite recursion is born after a failure in the first place

Ah! Very interesting :small_airplane:

**Comment by nrdxp** [comment]
So `nomadDeployNamespaces` should exist unless, and I am pulling the makes script directly from [our WIP branch](+https://github.com/input-output-hk/makes/tree/WIP-nomad) which contains all the needed bits from the Nomad PR as rebased on some of our own patches. So unless there is some typo somewhere, these the conditions for success should be met in this case?

**Comment by kamadorueda** [comment]
I just checked-in your branch and:

![image](https://user-images.githubusercontent.com/47480384/137047391-422ce3d9-9b05-437b-8676-627fa18c8ea9.png)

From what I see you added a module here: https://github.com/input-output-hk/makes/commit/d834344bd463b7684e89c73346862732f57a5b41

and it only defines:

```nix
{
  options = {
    deployNomad = {
      modules = lib.mkOption {
        default = { };
        type = lib.types.attrsOf (lib.types.submodule (_: {
          options = {
# ...
            namespace = lib.mkOption {
              type = lib.types.str;
            };
# ...
        }));
      };
    };
}
```

So you should not be configuring it like:  `nomadDeployNamespaces = xxx`

but more like this:

```nix
# makes.nix
{
  deployNomad.modules = {
    example = {
      namespace = "xxx";
      # ...
    };
  };
}
```

and then `m . /deployNomad/example`

**Comment by blaggacao** [comment]
Ha! Who had thought a forgotten rebase of mine / wrong commit would lead to an inifinte recoursion error. :smile:

@kamadorueda thanks for the excellent hunting down!

**Comment by kamadorueda** [comment]
This kind of things are gonna help with such debugging in future situations:

https://github.com/NixOS/nix/pull/5389
