### ISSUE TITLE
Using toBashMap at scale

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#746]
building '/nix/store/2c7h6nyhi5qr8mpxrq4w8y5wmiiwn6ay-make-template-for-as-bash-map.drv'...

while setting up the build environment: executing '/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/bash': Argument list too long

builder for '/nix/store/2c7h6nyhi5qr8mpxrq4w8y5wmiiwn6ay-make-template-for-as-bash-map.drv' failed with exit code 1

**Comment by dsalaza4** [comment]
Not relevant to us as of now, as derivations have lost value to us for most scenarios.
