### ISSUE TITLE
Add Scala formatter

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#753]
I was creating a few test files for checking vulnerabilities over Scala language, and found that scalafmt is very nice for formatting. It's also available on nixpkgs

So this would be very helpful, and also a good starting point for some guys in the enterprise world

**Comment by dsalaza4** [comment]
@drestrepom Is this complete?

**Comment by dsalaza4** [comment]
As discussed in #502, we will no longer support specific-purpose builtins.
