### ISSUE TITLE
Nix 2.4 is not unstable anymore

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#781]
Let's update https://github.com/fluidattacks/makes#getting-started to allow using `nix-env` when running `nix (Nix) 2.4` as it is the stable version now. 

It looks like expermiental commands are now available in the stable version:

```
$ nix profile
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override\
```

Let's also clarify that.

**Comment by kamadorueda** [comment]
Stable is now 2.6

![image](https://user-images.githubusercontent.com/47480384/152864972-85dbaea2-d4da-46ef-9170-2a6f15b5871d.png)
