### ISSUE TITLE
Exclude frontmatter from lintMarkdown

### ISSUE THREAD

**Issue by jpverde** [fluidattacks/makes#782]

**Comment by dsalaza4** [comment]
Is this for makes's own job or we are talking about the arg itself?

**Comment by jpverde** [comment]
Markdownlint doesn't have any rules to apply on frontmatter, but it still shows errors on these lines, I'm adding the arg to exclude it.

**Comment by dsalaza4** [comment]
Can't that be specified in the provided config?

**Comment by jpverde** [comment]
I tried that but it seems to not recognize the arg on the config file, the only way to make it work was by writing the arg on the command itself.
