### ISSUE TITLE
Support sorts

### ISSUE THREAD

**Issue by rrferog** [fluidattacks/makes#786]
## Problem to solve
It would be useful to use the sorts engine on every commit to determine how probable it is for the files submitted to be risky and optionally ask for approval to merge based on this.
Sorts product: https://gitlab.com/fluidattacks/product/-/tree/master/sorts

## Proposal
Create arg and module for Sorts in makes to have a simple way of adding sorts to the pipeline of a user's repository to check for potential vulnerabilities in each commit.

**Comment by dsalaza4** [comment]
Decided to create an independent solution for this.
