### ISSUE TITLE
Create module for scorecards

### ISSUE THREAD

**Issue by jpverde** [fluidattacks/makes#794]
use https://github.com/ossf/scorecard

**Comment by jpverde** [comment]
It seems like Scorecard runs some checks on the git repository configuration, so running the test locally is an incomplete test. I'm currently working on a solution to this.

**Comment by dsalaza4** [comment]
What I would like to do here is passing a github token to the scorecard cli, so makes can still call it as  builtin while keeping access to the github repository that wants to be reviewed.

**Comment by jpverde** [comment]
But why? The scorecard cli doesn't support a `token` option. This is the way it [authenticates](https://github.com/ossf/scorecard#authentication)
The command just takes the token from the actual environment, if it is a CI job you use the access token from the context of your CI environment. Making it use a token in the configuration will add a requirement to the module: managing secrets, which I think is unnecessary here.

**Comment by dsalaza4** [comment]
If it looks for a github envar by default, then everything it should be fine the way it is right now.
