### ISSUE TITLE
Test for makeTemplate replacement

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#813]
We've had several problems in the past with the substitution software used by `makeTemplate`, `rpl`.

Let's

1. Create a pipeline check that uses makeTemplate for replacing all kinds of special characters.
2. Consider replacing `rpl` with either `envsubst` or `sed`.

**Comment by GTrunSec** [comment]
I would like to use the `envsubst` as the default substitution. Also, we can parse the suffix of the file to the language that checks the final file's syntax.

**Comment by jpverde** [comment]
I don't think `envsubst` is the right take here, I tried to use it but the command just replaces every variable available. We decided to use `rpl` because of its simplicity, it just does the job. Can you share with us your approach using `envsubst`?

**Comment by GTrunSec** [comment]
First of all, there is some doubt about the namespace that uses makeTemplate, which should be named makeSubstitution. We usually use the languages like cue nix nickel to generate a template, then replace them with makeSubstitution to the final content. 

- workflow
![image](https://user-images.githubusercontent.com/21156405/156911454-1bd8451b-c666-4d18-abe7-4bb7cc153735.png)

- re-implement makeTemplate

```nix
=   2 │ threatbus-nomad-nixpkgs-nickel = makeTemplate {
=   1 │ │ name = "nomad-threatbus";
   11 │ │ format = "json";                                                                                               
=   1 │ │ args = [ "threatbus-nomad-nix.ncl" ];
=   2 │ │ path = ./tenzir/nomad;
=   3 │ };
=   4 
=   5 │ threatbus-nomad-nixpkgs-cue = makeTemplate {
=   6 │ │ name = "nomad-threatbus";
=   7 │ │ format = "yaml";
=   8 │ │ args = [ "jobs.dev" ];
=   9 │ │ path = ./tenzir/nomad;
=  10 │ };
   7 │ threatbus-nomad-nixpkgs-nix = makeTemplate {
=   8 │ │ name = "nomad-threatbus";
=   9 │ │ # terranix example                                                                                             
=  10 │ │ format = "nix";
=  11 │ │ args = [ "config.nix" ];
=  12 │ │ path = ./tenzir/nomad;
   13 │ };
```
![image](https://user-images.githubusercontent.com/21156405/156911467-5d887809-95c5-4d83-a26c-df8cab97fc13.png)


> I don't think envsubst is the right take here, I tried to use it but the command just replaces every variable available. 

Ye, I thought that we can support both specific substitution(replace) and environment variable set substitution. When using envsubst can point to a variable set that we no longer need the replace.

![image](https://user-images.githubusercontent.com/21156405/156911387-2f33340a-435f-42e3-9595-97d846dc2d6c.png)

**Comment by dsalaza4** [comment]
@GTrunSec  Regarding the changes you propose:

1. I think the name should be changed to `makeSubstitution` as it better describes what this builtin does.
2. Supporting different languages: I do not see what the gains of doing this are, as the purpose of `makeTemplate` is simply substituting arguments into a given file. If some sort of escaping is necessary for your resulting file to work, you should consider that. Supporting every language that's out there is simply not possible. What I would recommend here is writing the args you want to replace in a set and then running an escaping custom function for your specific scenario.
3. Supporting args from different data format files (json, yaml, etc): This would only increase complexity compared to directly keeping them in nix.
4. Using envsubst: I agree with @jpverde on this one. I currently do not see the gains of using `envsubst` other than making it easier to implement `3` (`envsubst < "source.txt" > "destination.txt"`).

Regarding `rpl` and `envsubst`... Now that we added the UTF-8 flag to `rpl` and it seems to be working fine now with all unicode characters, I would personally keep using `rpl` as it simply gets the job done.

Let me know if I am missing something. Thank you for your contribution! :+1: :zap:
