### ISSUE TITLE
Support nodejs modules from github

### ISSUE THREAD

**Issue by dacevedo12** [fluidattacks/makes#860]
npm supports installing directly from github repos, which comes in handy as sometimes, maintainers take a long time to publish new versions to npm

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#git-urls-as-dependencies
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#github-urls

perhaps the structure in the package-lock changes a bit, causing makes to fail when installing the deps

![image](https://user-images.githubusercontent.com/29694570/175054281-d72bb174-a653-4e93-ae35-a088ad65e41d.png)

```
error: attribute 'integrity' missing

       at /nix/store/hawaw7ivjjrq228iak21lvcjq7nxpax2-source/src/args/make-node-js-modules/default.nix:77:34:

           76|               value = {
           77|                 dist.integrity = versionAttrs.integrity;
             |                                  ^
           78|                 dist.tarball = versionAttrs.resolvedName;

       … while evaluating anonymous lambda

       at /nix/store/hawaw7ivjjrq228iak21lvcjq7nxpax2-source/src/args/make-derivation/default.nix:27:9:

           26|     builtins.mapAttrs
           27|     (k: v: (
             |         ^
           28|       if (hasPrefix "__" k) || (hasPrefix "env" k)

       … from call site

       … while evaluating the attribute 'envAll' of the derivation 'gatsby-source-cloudinary.json'

       at /nix/store/hawaw7ivjjrq228iak21lvcjq7nxpax2-source/src/args/make-derivation/default.nix:92:7:

           91|       builder = "${__nixpkgs__.bash}/bin/bash";
           92|       name = toDerivationName name;
             |       ^
           93|       outputs = ["out"];

       … while evaluating 'escapeShellArg'
```

Tested with `npm i --save https://github.com/cloudinary-devs/gatsby-source-cloudinary#19a2115fdf876c55ff74756e6dfd8d775bad636c`

**Comment by dsalaza4** [comment]
@dacevedo12 As we recently migrated to node2nix, it would be nice to tests if this works now.

**Comment by dacevedo12** [comment]
Seems node2nix is capable of it, but it doesn't find the git binary
```

error: builder for '...' failed with exit code 1;
       last 10 log lines:
       >   code: 'ENOENT',
       >   syscall: 'spawn git',
       >   path: 'git',
       >   spawnargs: [
       >     'clone',
       >     'ssh://git@github.com/cloudinary-devs/gatsby-source-cloudinary.git'
       >   ]
       > }
       >
       > Node.js v20.10.0
```

**Comment by dsalaza4** [comment]
@dacevedo12 

Maybe by adding `buildInputs` via `packageOverrides` as shown [here](https://makes.fluidattacks.com/api/extensions/node.js/?h=node2ni#__codelineno-2-17)

**Comment by dacevedo12** [comment]
It only worked at makes level (make-node-js-modules/default.nix), by adding __nixpkgs__.git

git via ssh doesn't work but that's a limitation from node2nix https://github.com/svanderburg/node2nix/issues/309

git via https works fine with the aforementioned patch

**Comment by dsalaza4** [comment]
@dacevedo12 A PR adding git to the builtin is welcome!

**Comment by dacevedo12** [comment]
Addressed in https://github.com/fluidattacks/makes/pull/1286

Thanks @dsalaza4 node2nix sure was an improvement!
