### ISSUE TITLE
cyclomatic complexity linter for bash

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#87]
Based on this: https://github.com/shellspec/shellmetrics ?

**Comment by dsalaza4** [comment]
It doesn't look like it supports failing based on parameters. I think we'll have to consider supporting a config file for specifying expected values and parsing the csv output it provides in order to validate compliance.

**Comment by kamadorueda** [comment]
Behold the all mighty GNU grep

**Comment by dsalaza4** [comment]
Maybe awk? It could work

**Comment by kamadorueda** [comment]
/lintWithLizard covers this and many more languages
