### ISSUE TITLE
Mypy strict config

### ISSUE THREAD

**Issue by danmur97** [fluidattacks/makes#939]
Add support for a more strict mypy configuration file (i.e. enable all checks).
I suggest to mark explicitly each config field, even if the default value is the desired one and can be omitted. This will secure the linter against default values changes and also serve as a reference (other than mypy docs) of what is checked on the code.

**Comment by sebas031811** [comment]
Hello, could I take it?
I have some questions...
What about config flags without default value (string field types)?
What kind of desc should I put by field ? 

Could it be like this?

![image](https://github.com/fluidattacks/makes/assets/132764573/13aaf0cd-88f4-4347-94f1-a2033d336478)

**Comment by dsalaza4** [comment]
@sebas031811 Instead of making stricter, I would suggest letting users specify the config they want just like we did with https://github.com/fluidattacks/makes/pull/1106

Something like:

```nix
{
  lintPython = {
    dirsOfModules = {
      makes = {
        config = {
          mypy = ./path-to-my-mypy-config.cfg;
          prospector = ./path-to-my-prospector-config.yaml;
        };
        python = "3.8";
        src = "/src/cli";
      };
    };
    imports = {
      cli = {
        config = "/src/cli/imports.cfg";
        src = "/src/cli";
      };
    };
    modules = {
      cliMain = {
        config = {
          mypy = ./path-to-my-mypy-config.cfg;
          prospector = ./path-to-my-prospector-config.yaml;
        };
        python = "3.8";
        src = "/src/cli/main";
      };
    };
  };
}
```

**Comment by sebas031811** [comment]
Hello @dsalaza4, Iḿ having an error with the suggested change ... 
The the files path change from _'/nix/store/xz7v2j88q7xi9yzgvffsn2c4q1skrpcj-makes-g5a190jm/src/evaluator/modules/lint-python/settings-mypy.cfg'_ to _'/tmp/makes-0lvy6dej/settings-mypy.cfg'_ so I get _error: getting status of '/tmp/makes-0lvy6dej/settings-mypy.cfg': No such file or directory_

**Comment by dsalaza4** [comment]
Maybe you didn't `git add` the new files you added?

Please read https://makes.fluidattacks.com/contributing/#testing-your-local-changes

**Comment by dsalaza4** [comment]
@danmur97 lintPython now supports custom configs: https://makes.fluidattacks.com/api/builtins/lint/?h=lint#lintpython

Closing this issue.
