### ISSUE TITLE
Consolidate documentation on the website

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#940]
The website is nice, it's well structured, has a search bar, and is generally easier to navigate than the long readme we currently have, it's also easier to point someone to a specific part of the documentation on the web than in the readme, and it's also easier to locate content, as the table of contents is to the side instead of to the top

**Comment by dsalaza4** [comment]
I will prioritize this as I think that having a simple-as-possible readme will:

1. Considerably reduce the learning curve.
2. Align Makes with our philosophy of `learn by doing`.
