### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by dacevedo12** [fluidattacks/makes#957]
makeNodeJsModule and makeNodeJsEnvironment don't work well with ECMAScript modules (.mjs files) as they don't support resolution from directories specified in `NODE_PATH` https://nodejs.org/api/esm.html#no-node_path

ESM are likely to become more common with time so this would be a good improvement to future-proof nodejs support

**Comment by dacevedo12** [comment]
to be clear, this is not an issue specific to makes but I'll give it a try to improve nodejs support here

**Comment by kamadorueda** [comment]
Give this a look: https://github.com/nix-community/dream2nix

From what I have heard they have very solid support for NPM now

**Comment by dsalaza4** [comment]
Closing in favor of #721
