### ISSUE TITLE
[compute-on-aws-batch] add support for evaluateOnExit on RetryStrategy

### ISSUE THREAD

**Issue by danmur97** [fluidattacks/makes#972]
`compute-on-aws-batch` only supports attempts parameter for a batch job. Add conditions of retry through evaluateOnExit input ([aws docs](https://docs.aws.amazon.com/batch/latest/APIReference/API_RetryStrategy.html), [aws cli](https://docs.aws.amazon.com/cli/latest/reference/batch/submit-job.html))

**Comment by dsalaza4** [comment]
As discussed in #502, specific-purpose builtins will no longer be supported. We will most likely mode `computeOnAwsBatch` to universe and adapt it to our needs from there.
