### ISSUE TITLE
Even more reproducibility

### ISSUE THREAD

**Issue by kamadorueda** [fluidattacks/makes#976]
1. Make the container run as user by default, and instead make a feature flag run it as root
2. Make sure sandbox is enabled in the container
3. Update Nix, and make sure only one version is in the final container
4. Document the extra steps needed so that a Nix with Daemon installation works, so that we can suggest people to use this kind of install

**Comment by dsalaza4** [comment]
For simplicity, we're sticking to the same approach used by the nixos containers. If such containers eventually reach a full-purity state, we will benefit from them. Otherwise, we'll inherit the impurity.
