### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by dsalaza4** [fluidattacks/makes#985]
Let's add support for building Python environments using Python 3.11

**Comment by dsalaza4** [comment]
I will be dropping Python 3.7 support in order to be able to update numpy to its latest version.

**Comment by dsalaza4** [comment]
Licensing was improved as well.

**Comment by dsalaza4** [comment]
I will also work on updating all builtins that use older python versions.

**Comment by dsalaza4** [comment]
@kamadorueda Take a look at this:

https://github.com/fluidattacks/makes/blob/main/makes/cli/env/runtime/pypi/pypi-sources.yaml#L5

https://pypi.org/project/textual/#history

They changed so much in just in 8 months! 

I tried to update it but mypy started to fail with weird errors. I think that the textual code written for the TUI is actually no longer compatible with that latest version. 😆

This looks like one of the cons of adopting such early-stage libraries, they change too much if they haven't gained enough stability.

I will open a separate issue for upgrading Makes to Python 3.11 and updating all its pypi dependencies to the current version.

**Comment by kamadorueda** [comment]
let's upgrade it to Rust ;)

btw I discovered this project today: https://github.com/pvolok/mprocs
maybe useful for the dev environments

**Comment by kamadorueda** [comment]
maybe would be nice to ask people if they find the TUI useful first, if not, then using a CLI with emojis would be equally good for less. If they find the TUI useful but migrating to the newer version of textual is hard, then we can replace the useful features of the TUI with an equivalent in the CLI, for example, TUI visual search -> terminal autocompletion. Some market research would help taking a decision here

**Comment by dsalaza4** [comment]
https://github.com/fluidattacks/makes/issues/989

**Comment by dsalaza4** [comment]
We now support Python 3.11 and all builtins were updated to such version. Makes still uses Python 3.10 due the TUI issue mentioned before.

**Comment by dsalaza4** [comment]
There are issues when running lintPython using 3.11: https://gitlab.com/fluidattacks/universe/-/jobs/3562147270

I will try updating nixpkgs so we get an even newer Python version.

**Comment by dsalaza4** [comment]
Updating nixpkgs breaking lintNix. I ended up not having to do it as the error in lintPython was due to incompatible pypi libraries. I managed to solve it in https://github.com/fluidattacks/makes/pull/992
