### ISSUE TITLE
lint python missing django

### ISSUE THREAD

**Issue by danmur97** [fluidattacks/makes#993]
`m . /lintPython/module/***` fails with:
![image](https://user-images.githubusercontent.com/42251914/212186305-2a9208fb-d938-45cf-a5a7-5c43789da5ef.png)

This seems due to django added dependency to pylint plugins. [see this post](https://www.appsloveworld.com/django/100/101/python-click-project-django-is-not-available-on-the-pythonpath-error).

**Comment by dsalaza4** [comment]
As discussed in #502, we will no longer support specific-purpose builtins. lintPython will be deprecated.
